// =============================================================================
// AUTO-GENERATED FILE - DO NOT EDIT
// This file is generated by PacketGenerator. Any manual changes will be lost.
// =============================================================================
#pragma once

namespace packet_id
{
	enum eChatPacketId : uint16
	{
        C2S_CHAT_REQ = 1,
        S2C_CHAT_NOT = 2,
        S2S_REALM_CHAT_SUBMIT_NOT = 3,
        S2S_REALM_CHAT_DELIVER_NOT = 4,
	};


	enum eEchoPacketId : uint16
	{
        C2S_ECHO_REQ = 1,
        S2C_ECHO_RES = 2,
	};


	enum eGameSessionPacketId : uint16
	{
        S2S_GAME_SESSION_ENTER_NOT = 1,
        S2S_GAME_SESSION_ENTER_RES = 2,
        S2S_GAME_SESSION_LEAVE_NOT = 3,
        S2S_GAME_SESSION_SYNC_ENTER_NOT = 4,
        S2S_GAME_SESSION_SYNC_LEAVE_NOT = 5,
        S2S_RELAY_TO_CLIENT_NOT = 6,
        S2S_RELAY_TO_WORLD_NOT = 7,
	};


	enum eHeartbeatPacketId : uint16
	{
        C2S_HEARTBEAT_NOT = 1,
	};


	enum eLoginPacketId : uint16
	{
        C2S_LOGIN_REQ = 1,
        S2C_LOGIN_RES = 2,
        S2C_KICK_NOT = 3,
	};


	enum eMovementPacketId : uint16
	{
        C2S_MOVE_INPUT_NOT = 1,
        S2C_MOVE_RESULT_NOT = 2,
        S2C_ENTITY_SNAPSHOT_NOT = 3,
        S2C_ENTITY_ENTER_NOT = 4,
        S2C_ENTITY_LEAVE_NOT = 5,
        C2S_SPAWN_POSITION_REQ = 6,
        S2C_SPAWN_POSITION_RES = 7,
        C2S_MOVE_TO_POSITION_REQ = 8,
        S2C_MOVE_PATH_RES = 9,
        S2C_POSITION_CORRECTION_NOT = 10,
	};


	enum eRealmPacketId : uint16
	{
        C2S_REALM_LIST_REQ = 1,
        S2C_REALM_LIST_RES = 2,
        C2S_REALM_SELECT_REQ = 3,
        S2C_REALM_SELECT_RES = 4,
	};


	enum eServerHeartbeatPacketId : uint16
	{
        S2S_HEARTBEAT_NOT = 1,
	};

}