// =============================================================================
// AUTO-GENERATED FILE - DO NOT EDIT
// This file is generated by PacketGenerator. Any manual changes will be lost.
// =============================================================================
// ReSharper disable CppInconsistentNaming
#pragma once

#include <cstring>
#include <vector>

#ifdef _UNREAL_

#include "Network/CppNetEngine/NetEngineWrapper.h"
#include "Network/ProtocolHeader/ProtocolWrapper.h"

#else

#include "Enum.pb.h"
#include "Struct.pb.h"
#include "PacketOption.pb.h"
#include "PacketId.h"
#include "GameSession.pb.h"

#endif

class GameSessionPacketHandler
{
public:

	using PacketHandle = std::function<bool(const uint16, const byte*, const PacketSessionRef&)>;

	static constexpr uint32 MAKE_PACKET_HEADER_ID(const uint16 serviceType, const uint16 packetId)
	{
		return (static_cast<uint32>(serviceType) << 16) | static_cast<uint32>(packetId);
	}

	static void Init()
	{
		sPacketHandleMap[packet_id::eGameSessionPacketId::S2S_GAME_SESSION_ENTER_RES] = [](const uint16 size, const byte* pBuffer, const PacketSessionRef& pSession) -> bool
		{
			return HandlePacket<Protocol::S2S_GAME_SESSION_ENTER_RES>(size, pBuffer, pSession, HANDLE_S2S_GAME_SESSION_ENTER_RES);
		};
		sPacketHandleMap[packet_id::eGameSessionPacketId::S2S_RELAY_TO_CLIENT_NOT] = [](const uint16 size, const byte* pBuffer, const PacketSessionRef& pSession) -> bool
		{
			return HandlePacket<Protocol::S2S_RELAY_TO_CLIENT_NOT>(size, pBuffer, pSession, HANDLE_S2S_RELAY_TO_CLIENT_NOT);
		};

	}

	static bool HandlePacket(const uint16 size, const uint16 packetId, const byte* pBuffer, const PacketSessionRef& pSession)
	{
		const auto iter = sPacketHandleMap.find(packetId);
		if (iter != sPacketHandleMap.end())
		{
			if (!Validate(pSession))
			{
				return false;
			}

			return iter->second(size, pBuffer, pSession);
		}

		return HANDLE_PACKET_ID_INVALID(size, packetId, pBuffer, pSession);
	}

	static bool Validate(const PacketSessionRef& pSession);
	static bool HANDLE_PACKET_ID_INVALID(const uint16 size, const uint16 packetId, const byte* pBuffer, const PacketSessionRef& pSession);
	static bool HANDLE_S2S_GAME_SESSION_ENTER_RES(const Protocol::S2S_GAME_SESSION_ENTER_RES& packet, const PacketSessionRef& pSession);
	static bool HANDLE_S2S_RELAY_TO_CLIENT_NOT(const Protocol::S2S_RELAY_TO_CLIENT_NOT& packet, const PacketSessionRef& pSession);
	

	static NetSendBufferRef MakeSendBuffer(const Protocol::S2S_GAME_SESSION_ENTER_NOT& packet) { return MakeSendBuffer(packet, packet_id::S2S_GAME_SESSION_ENTER_NOT); }
	static NetSendBufferRef MakeSendBuffer(const Protocol::S2S_GAME_SESSION_LEAVE_NOT& packet) { return MakeSendBuffer(packet, packet_id::S2S_GAME_SESSION_LEAVE_NOT); }
	static NetSendBufferRef MakeSendBuffer(const Protocol::S2S_RELAY_TO_WORLD_NOT& packet) { return MakeSendBuffer(packet, packet_id::S2S_RELAY_TO_WORLD_NOT); }
	

private:

	template<typename PacketType, typename Handle>
	static bool HandlePacket(const uint16 size, const byte* pBuffer, const PacketSessionRef& pSession, Handle handlePacket)
	{
		const int32 headerBytes = static_cast<int32>(sizeof(PacketHeader));
		const int32 bodyBytes = static_cast<int32>(size) - headerBytes;
		if (bodyBytes < 0)
		{
			return false;
		}

		if (pBuffer == nullptr)
		{
			return false;
		}

		// IOCP 수신 버퍼를 직접 Parse 대상으로 쓰지 않음 — 릴레이/재사용 경계에서 힙·별칭 이슈로 AV 방지
		std::vector<byte> body(static_cast<size_t>(bodyBytes));
		if (bodyBytes > 0)
		{
			std::memcpy(body.data(), pBuffer + headerBytes, static_cast<size_t>(bodyBytes));
		}

		PacketType packet{};
		if (packet.ParseFromArray(body.data(), bodyBytes) == false)
		{
			return false;
		}

		return handlePacket(packet, pSession);
	}

	template<typename T>
	static NetSendBufferRef MakeSendBuffer(const T& packet, const uint16 packetId)
	{
		const uint16 dataSize = static_cast<uint16>(packet.ByteSizeLong());
		const uint32 rawPacketSize = static_cast<uint32>(dataSize) + sizeof(PacketHeader);

		if (rawPacketSize > std::numeric_limits<uint16>::max())
		{
			NET_ENGINE_LOG_FATAL("MakeSendBuffer Size Overflow, packetId : {}, packetSize : {}", packetId, rawPacketSize);
			CrashReporter::Crash();
		}

		const uint16 packetSize = static_cast<uint16>(rawPacketSize);

		auto sendBuffer = cpp_net_engine::MakeSendBuffer(packetSize);

		byte* pBuffer = sendBuffer->Reserve(packetSize);
		if (pBuffer == nullptr)
		{
			NET_ENGINE_LOG_FATAL("MakeSendBuffer sendBuffer->Reserve(packetSize) is failed");
			CrashReporter::Crash();
		}

		auto* header = reinterpret_cast<PacketHeader*>(pBuffer);
		header->size = packetSize;
		header->id = MAKE_PACKET_HEADER_ID(Protocol::eServiceType::SERVICE_TYPE_GAME_SESSION, packetId);
		if (!packet.SerializeToArray(&header[1], dataSize))
		{
			NET_ENGINE_LOG_FATAL("GameSession::MakeSendBuffer SerializeToArray is Failed, &header[1] : {}, packetId : {}, dataSize : {}", fmt::ptr(&header[1]), header->id, dataSize);
			CrashReporter::Crash();
		}

		sendBuffer->Commit(packetSize);

		return sendBuffer;
	}

	inline static HashMap<uint16, PacketHandle> sPacketHandleMap;
};