// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Echo.proto

#include "Echo.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Protocol {
PROTOBUF_CONSTEXPR C2S_ECHO_REQ::C2S_ECHO_REQ(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.echomsg_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct C2S_ECHO_REQDefaultTypeInternal {
  PROTOBUF_CONSTEXPR C2S_ECHO_REQDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~C2S_ECHO_REQDefaultTypeInternal() {}
  union {
    C2S_ECHO_REQ _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 C2S_ECHO_REQDefaultTypeInternal _C2S_ECHO_REQ_default_instance_;
PROTOBUF_CONSTEXPR S2C_ECHO_RES::S2C_ECHO_RES(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.echomsg_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct S2C_ECHO_RESDefaultTypeInternal {
  PROTOBUF_CONSTEXPR S2C_ECHO_RESDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~S2C_ECHO_RESDefaultTypeInternal() {}
  union {
    S2C_ECHO_RES _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S2C_ECHO_RESDefaultTypeInternal _S2C_ECHO_RES_default_instance_;
}  // namespace Protocol
static ::_pb::Metadata file_level_metadata_Echo_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_Echo_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Echo_2eproto = nullptr;

const uint32_t TableStruct_Echo_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::C2S_ECHO_REQ, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::C2S_ECHO_REQ, _impl_.echomsg_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::S2C_ECHO_RES, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::S2C_ECHO_RES, _impl_.echomsg_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Protocol::C2S_ECHO_REQ)},
  { 7, -1, -1, sizeof(::Protocol::S2C_ECHO_RES)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Protocol::_C2S_ECHO_REQ_default_instance_._instance,
  &::Protocol::_S2C_ECHO_RES_default_instance_._instance,
};

const char descriptor_table_protodef_Echo_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\nEcho.proto\022\010Protocol\032\022PacketOption.pro"
  "to\")\n\014C2S_ECHO_REQ\022\017\n\007echoMsg\030\001 \001(\t:\010\240\265\030"
  "\002\250\265\030\003\")\n\014S2C_ECHO_RES\022\017\n\007echoMsg\030\001 \001(\t:\010"
  "\240\265\030\003\250\265\030\002B\031\210\265\030\001\222\265\030\021EchoPacketHandlerb\006pro"
  "to3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_Echo_2eproto_deps[1] = {
  &::descriptor_table_PacketOption_2eproto,
};
static ::_pbi::once_flag descriptor_table_Echo_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Echo_2eproto = {
    false, false, 163, descriptor_table_protodef_Echo_2eproto,
    "Echo.proto",
    &descriptor_table_Echo_2eproto_once, descriptor_table_Echo_2eproto_deps, 1, 2,
    schemas, file_default_instances, TableStruct_Echo_2eproto::offsets,
    file_level_metadata_Echo_2eproto, file_level_enum_descriptors_Echo_2eproto,
    file_level_service_descriptors_Echo_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Echo_2eproto_getter() {
  return &descriptor_table_Echo_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Echo_2eproto(&descriptor_table_Echo_2eproto);
namespace Protocol {

// ===================================================================

class C2S_ECHO_REQ::_Internal {
 public:
};

C2S_ECHO_REQ::C2S_ECHO_REQ(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.C2S_ECHO_REQ)
}
C2S_ECHO_REQ::C2S_ECHO_REQ(const C2S_ECHO_REQ& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  C2S_ECHO_REQ* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.echomsg_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.echomsg_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.echomsg_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_echomsg().empty()) {
    _this->_impl_.echomsg_.Set(from._internal_echomsg(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:Protocol.C2S_ECHO_REQ)
}

inline void C2S_ECHO_REQ::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.echomsg_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.echomsg_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.echomsg_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

C2S_ECHO_REQ::~C2S_ECHO_REQ() {
  // @@protoc_insertion_point(destructor:Protocol.C2S_ECHO_REQ)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void C2S_ECHO_REQ::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.echomsg_.Destroy();
}

void C2S_ECHO_REQ::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void C2S_ECHO_REQ::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.C2S_ECHO_REQ)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.echomsg_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* C2S_ECHO_REQ::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string echoMsg = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_echomsg();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Protocol.C2S_ECHO_REQ.echoMsg"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* C2S_ECHO_REQ::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.C2S_ECHO_REQ)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string echoMsg = 1;
  if (!this->_internal_echomsg().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_echomsg().data(), static_cast<int>(this->_internal_echomsg().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Protocol.C2S_ECHO_REQ.echoMsg");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_echomsg(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.C2S_ECHO_REQ)
  return target;
}

size_t C2S_ECHO_REQ::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.C2S_ECHO_REQ)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string echoMsg = 1;
  if (!this->_internal_echomsg().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_echomsg());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData C2S_ECHO_REQ::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    C2S_ECHO_REQ::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*C2S_ECHO_REQ::GetClassData() const { return &_class_data_; }


void C2S_ECHO_REQ::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<C2S_ECHO_REQ*>(&to_msg);
  auto& from = static_cast<const C2S_ECHO_REQ&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.C2S_ECHO_REQ)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_echomsg().empty()) {
    _this->_internal_set_echomsg(from._internal_echomsg());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void C2S_ECHO_REQ::CopyFrom(const C2S_ECHO_REQ& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.C2S_ECHO_REQ)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool C2S_ECHO_REQ::IsInitialized() const {
  return true;
}

void C2S_ECHO_REQ::InternalSwap(C2S_ECHO_REQ* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.echomsg_, lhs_arena,
      &other->_impl_.echomsg_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata C2S_ECHO_REQ::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Echo_2eproto_getter, &descriptor_table_Echo_2eproto_once,
      file_level_metadata_Echo_2eproto[0]);
}

// ===================================================================

class S2C_ECHO_RES::_Internal {
 public:
};

S2C_ECHO_RES::S2C_ECHO_RES(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.S2C_ECHO_RES)
}
S2C_ECHO_RES::S2C_ECHO_RES(const S2C_ECHO_RES& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  S2C_ECHO_RES* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.echomsg_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.echomsg_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.echomsg_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_echomsg().empty()) {
    _this->_impl_.echomsg_.Set(from._internal_echomsg(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:Protocol.S2C_ECHO_RES)
}

inline void S2C_ECHO_RES::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.echomsg_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.echomsg_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.echomsg_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

S2C_ECHO_RES::~S2C_ECHO_RES() {
  // @@protoc_insertion_point(destructor:Protocol.S2C_ECHO_RES)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void S2C_ECHO_RES::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.echomsg_.Destroy();
}

void S2C_ECHO_RES::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void S2C_ECHO_RES::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.S2C_ECHO_RES)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.echomsg_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* S2C_ECHO_RES::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string echoMsg = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_echomsg();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "Protocol.S2C_ECHO_RES.echoMsg"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* S2C_ECHO_RES::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.S2C_ECHO_RES)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string echoMsg = 1;
  if (!this->_internal_echomsg().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_echomsg().data(), static_cast<int>(this->_internal_echomsg().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Protocol.S2C_ECHO_RES.echoMsg");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_echomsg(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.S2C_ECHO_RES)
  return target;
}

size_t S2C_ECHO_RES::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.S2C_ECHO_RES)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string echoMsg = 1;
  if (!this->_internal_echomsg().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_echomsg());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData S2C_ECHO_RES::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    S2C_ECHO_RES::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*S2C_ECHO_RES::GetClassData() const { return &_class_data_; }


void S2C_ECHO_RES::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<S2C_ECHO_RES*>(&to_msg);
  auto& from = static_cast<const S2C_ECHO_RES&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.S2C_ECHO_RES)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_echomsg().empty()) {
    _this->_internal_set_echomsg(from._internal_echomsg());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void S2C_ECHO_RES::CopyFrom(const S2C_ECHO_RES& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.S2C_ECHO_RES)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S2C_ECHO_RES::IsInitialized() const {
  return true;
}

void S2C_ECHO_RES::InternalSwap(S2C_ECHO_RES* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.echomsg_, lhs_arena,
      &other->_impl_.echomsg_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata S2C_ECHO_RES::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Echo_2eproto_getter, &descriptor_table_Echo_2eproto_once,
      file_level_metadata_Echo_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Protocol::C2S_ECHO_REQ*
Arena::CreateMaybeMessage< ::Protocol::C2S_ECHO_REQ >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::C2S_ECHO_REQ >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::S2C_ECHO_RES*
Arena::CreateMaybeMessage< ::Protocol::S2C_ECHO_RES >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::S2C_ECHO_RES >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
