// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Enum.proto
// Protobuf C++ Version: 5.29.5

#ifndef Enum_2eproto_2epb_2eh
#define Enum_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/descriptor.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Enum_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_Enum_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_Enum_2eproto;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace Protocol {
enum eRole : int {
  ROLE_NONE = 0,
  CLIENT = 1,
  GAME_SERVER = 2,
  eRole_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  eRole_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool eRole_IsValid(int value);
extern const uint32_t eRole_internal_data_[];
constexpr eRole eRole_MIN = static_cast<eRole>(0);
constexpr eRole eRole_MAX = static_cast<eRole>(2);
constexpr int eRole_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor*
eRole_descriptor();
template <typename T>
const std::string& eRole_Name(T value) {
  static_assert(std::is_same<T, eRole>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to eRole_Name().");
  return eRole_Name(static_cast<eRole>(value));
}
template <>
inline const std::string& eRole_Name(eRole value) {
  return ::google::protobuf::internal::NameOfDenseEnum<eRole_descriptor,
                                                 0, 2>(
      static_cast<int>(value));
}
inline bool eRole_Parse(absl::string_view name, eRole* value) {
  return ::google::protobuf::internal::ParseNamedEnum<eRole>(
      eRole_descriptor(), name, value);
}

// ===================================================================



// ===================================================================



static const int kSenderFieldNumber = 50000;
extern ::google::protobuf::internal::ExtensionIdentifier<
    ::google::protobuf::MessageOptions, ::google::protobuf::internal::EnumTypeTraits< ::Protocol::eRole, ::Protocol::eRole_IsValid>, 14,
    false>
    sender;
static const int kReceiverFieldNumber = 50001;
extern ::google::protobuf::internal::ExtensionIdentifier<
    ::google::protobuf::MessageOptions, ::google::protobuf::internal::EnumTypeTraits< ::Protocol::eRole, ::Protocol::eRole_IsValid>, 14,
    false>
    receiver;

// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::Protocol::eRole> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::Protocol::eRole>() {
  return ::Protocol::eRole_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // Enum_2eproto_2epb_2eh
