// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameSession.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_GameSession_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_GameSession_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Enum.pb.h"
#include "PacketOption.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_GameSession_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_GameSession_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_GameSession_2eproto;
namespace Protocol {
class S2S_GAME_SESSION_ENTER_NOT;
struct S2S_GAME_SESSION_ENTER_NOTDefaultTypeInternal;
extern S2S_GAME_SESSION_ENTER_NOTDefaultTypeInternal _S2S_GAME_SESSION_ENTER_NOT_default_instance_;
class S2S_GAME_SESSION_ENTER_RES;
struct S2S_GAME_SESSION_ENTER_RESDefaultTypeInternal;
extern S2S_GAME_SESSION_ENTER_RESDefaultTypeInternal _S2S_GAME_SESSION_ENTER_RES_default_instance_;
class S2S_GAME_SESSION_LEAVE_NOT;
struct S2S_GAME_SESSION_LEAVE_NOTDefaultTypeInternal;
extern S2S_GAME_SESSION_LEAVE_NOTDefaultTypeInternal _S2S_GAME_SESSION_LEAVE_NOT_default_instance_;
class S2S_GAME_SESSION_SYNC_ENTER_NOT;
struct S2S_GAME_SESSION_SYNC_ENTER_NOTDefaultTypeInternal;
extern S2S_GAME_SESSION_SYNC_ENTER_NOTDefaultTypeInternal _S2S_GAME_SESSION_SYNC_ENTER_NOT_default_instance_;
class S2S_GAME_SESSION_SYNC_LEAVE_NOT;
struct S2S_GAME_SESSION_SYNC_LEAVE_NOTDefaultTypeInternal;
extern S2S_GAME_SESSION_SYNC_LEAVE_NOTDefaultTypeInternal _S2S_GAME_SESSION_SYNC_LEAVE_NOT_default_instance_;
class S2S_RELAY_TO_CLIENT_NOT;
struct S2S_RELAY_TO_CLIENT_NOTDefaultTypeInternal;
extern S2S_RELAY_TO_CLIENT_NOTDefaultTypeInternal _S2S_RELAY_TO_CLIENT_NOT_default_instance_;
class S2S_RELAY_TO_WORLD_NOT;
struct S2S_RELAY_TO_WORLD_NOTDefaultTypeInternal;
extern S2S_RELAY_TO_WORLD_NOTDefaultTypeInternal _S2S_RELAY_TO_WORLD_NOT_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::S2S_GAME_SESSION_ENTER_NOT* Arena::CreateMaybeMessage<::Protocol::S2S_GAME_SESSION_ENTER_NOT>(Arena*);
template<> ::Protocol::S2S_GAME_SESSION_ENTER_RES* Arena::CreateMaybeMessage<::Protocol::S2S_GAME_SESSION_ENTER_RES>(Arena*);
template<> ::Protocol::S2S_GAME_SESSION_LEAVE_NOT* Arena::CreateMaybeMessage<::Protocol::S2S_GAME_SESSION_LEAVE_NOT>(Arena*);
template<> ::Protocol::S2S_GAME_SESSION_SYNC_ENTER_NOT* Arena::CreateMaybeMessage<::Protocol::S2S_GAME_SESSION_SYNC_ENTER_NOT>(Arena*);
template<> ::Protocol::S2S_GAME_SESSION_SYNC_LEAVE_NOT* Arena::CreateMaybeMessage<::Protocol::S2S_GAME_SESSION_SYNC_LEAVE_NOT>(Arena*);
template<> ::Protocol::S2S_RELAY_TO_CLIENT_NOT* Arena::CreateMaybeMessage<::Protocol::S2S_RELAY_TO_CLIENT_NOT>(Arena*);
template<> ::Protocol::S2S_RELAY_TO_WORLD_NOT* Arena::CreateMaybeMessage<::Protocol::S2S_RELAY_TO_WORLD_NOT>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class S2S_GAME_SESSION_ENTER_NOT final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S2S_GAME_SESSION_ENTER_NOT) */ {
 public:
  inline S2S_GAME_SESSION_ENTER_NOT() : S2S_GAME_SESSION_ENTER_NOT(nullptr) {}
  ~S2S_GAME_SESSION_ENTER_NOT() override;
  explicit PROTOBUF_CONSTEXPR S2S_GAME_SESSION_ENTER_NOT(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S2S_GAME_SESSION_ENTER_NOT(const S2S_GAME_SESSION_ENTER_NOT& from);
  S2S_GAME_SESSION_ENTER_NOT(S2S_GAME_SESSION_ENTER_NOT&& from) noexcept
    : S2S_GAME_SESSION_ENTER_NOT() {
    *this = ::std::move(from);
  }

  inline S2S_GAME_SESSION_ENTER_NOT& operator=(const S2S_GAME_SESSION_ENTER_NOT& from) {
    CopyFrom(from);
    return *this;
  }
  inline S2S_GAME_SESSION_ENTER_NOT& operator=(S2S_GAME_SESSION_ENTER_NOT&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S2S_GAME_SESSION_ENTER_NOT& default_instance() {
    return *internal_default_instance();
  }
  static inline const S2S_GAME_SESSION_ENTER_NOT* internal_default_instance() {
    return reinterpret_cast<const S2S_GAME_SESSION_ENTER_NOT*>(
               &_S2S_GAME_SESSION_ENTER_NOT_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(S2S_GAME_SESSION_ENTER_NOT& a, S2S_GAME_SESSION_ENTER_NOT& b) {
    a.Swap(&b);
  }
  inline void Swap(S2S_GAME_SESSION_ENTER_NOT* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S2S_GAME_SESSION_ENTER_NOT* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S2S_GAME_SESSION_ENTER_NOT* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S2S_GAME_SESSION_ENTER_NOT>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S2S_GAME_SESSION_ENTER_NOT& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S2S_GAME_SESSION_ENTER_NOT& from) {
    S2S_GAME_SESSION_ENTER_NOT::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S2S_GAME_SESSION_ENTER_NOT* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S2S_GAME_SESSION_ENTER_NOT";
  }
  protected:
  explicit S2S_GAME_SESSION_ENTER_NOT(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAccountIdFieldNumber = 1,
    kGatewaySessionIdFieldNumber = 2,
    kGatewayServerIdFieldNumber = 3,
  };
  // uint64 accountId = 1;
  void clear_accountid();
  uint64_t accountid() const;
  void set_accountid(uint64_t value);
  private:
  uint64_t _internal_accountid() const;
  void _internal_set_accountid(uint64_t value);
  public:

  // uint64 gatewaySessionId = 2;
  void clear_gatewaysessionid();
  uint64_t gatewaysessionid() const;
  void set_gatewaysessionid(uint64_t value);
  private:
  uint64_t _internal_gatewaysessionid() const;
  void _internal_set_gatewaysessionid(uint64_t value);
  public:

  // int32 gatewayServerId = 3;
  void clear_gatewayserverid();
  int32_t gatewayserverid() const;
  void set_gatewayserverid(int32_t value);
  private:
  int32_t _internal_gatewayserverid() const;
  void _internal_set_gatewayserverid(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S2S_GAME_SESSION_ENTER_NOT)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t accountid_;
    uint64_t gatewaysessionid_;
    int32_t gatewayserverid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_GameSession_2eproto;
};
// -------------------------------------------------------------------

class S2S_GAME_SESSION_ENTER_RES final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S2S_GAME_SESSION_ENTER_RES) */ {
 public:
  inline S2S_GAME_SESSION_ENTER_RES() : S2S_GAME_SESSION_ENTER_RES(nullptr) {}
  ~S2S_GAME_SESSION_ENTER_RES() override;
  explicit PROTOBUF_CONSTEXPR S2S_GAME_SESSION_ENTER_RES(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S2S_GAME_SESSION_ENTER_RES(const S2S_GAME_SESSION_ENTER_RES& from);
  S2S_GAME_SESSION_ENTER_RES(S2S_GAME_SESSION_ENTER_RES&& from) noexcept
    : S2S_GAME_SESSION_ENTER_RES() {
    *this = ::std::move(from);
  }

  inline S2S_GAME_SESSION_ENTER_RES& operator=(const S2S_GAME_SESSION_ENTER_RES& from) {
    CopyFrom(from);
    return *this;
  }
  inline S2S_GAME_SESSION_ENTER_RES& operator=(S2S_GAME_SESSION_ENTER_RES&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S2S_GAME_SESSION_ENTER_RES& default_instance() {
    return *internal_default_instance();
  }
  static inline const S2S_GAME_SESSION_ENTER_RES* internal_default_instance() {
    return reinterpret_cast<const S2S_GAME_SESSION_ENTER_RES*>(
               &_S2S_GAME_SESSION_ENTER_RES_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(S2S_GAME_SESSION_ENTER_RES& a, S2S_GAME_SESSION_ENTER_RES& b) {
    a.Swap(&b);
  }
  inline void Swap(S2S_GAME_SESSION_ENTER_RES* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S2S_GAME_SESSION_ENTER_RES* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S2S_GAME_SESSION_ENTER_RES* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S2S_GAME_SESSION_ENTER_RES>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S2S_GAME_SESSION_ENTER_RES& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S2S_GAME_SESSION_ENTER_RES& from) {
    S2S_GAME_SESSION_ENTER_RES::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S2S_GAME_SESSION_ENTER_RES* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S2S_GAME_SESSION_ENTER_RES";
  }
  protected:
  explicit S2S_GAME_SESSION_ENTER_RES(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAccountIdFieldNumber = 1,
    kResultFieldNumber = 2,
  };
  // uint64 accountId = 1;
  void clear_accountid();
  uint64_t accountid() const;
  void set_accountid(uint64_t value);
  private:
  uint64_t _internal_accountid() const;
  void _internal_set_accountid(uint64_t value);
  public:

  // .Protocol.eGameSessionResult result = 2;
  void clear_result();
  ::Protocol::eGameSessionResult result() const;
  void set_result(::Protocol::eGameSessionResult value);
  private:
  ::Protocol::eGameSessionResult _internal_result() const;
  void _internal_set_result(::Protocol::eGameSessionResult value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S2S_GAME_SESSION_ENTER_RES)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t accountid_;
    int result_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_GameSession_2eproto;
};
// -------------------------------------------------------------------

class S2S_GAME_SESSION_LEAVE_NOT final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S2S_GAME_SESSION_LEAVE_NOT) */ {
 public:
  inline S2S_GAME_SESSION_LEAVE_NOT() : S2S_GAME_SESSION_LEAVE_NOT(nullptr) {}
  ~S2S_GAME_SESSION_LEAVE_NOT() override;
  explicit PROTOBUF_CONSTEXPR S2S_GAME_SESSION_LEAVE_NOT(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S2S_GAME_SESSION_LEAVE_NOT(const S2S_GAME_SESSION_LEAVE_NOT& from);
  S2S_GAME_SESSION_LEAVE_NOT(S2S_GAME_SESSION_LEAVE_NOT&& from) noexcept
    : S2S_GAME_SESSION_LEAVE_NOT() {
    *this = ::std::move(from);
  }

  inline S2S_GAME_SESSION_LEAVE_NOT& operator=(const S2S_GAME_SESSION_LEAVE_NOT& from) {
    CopyFrom(from);
    return *this;
  }
  inline S2S_GAME_SESSION_LEAVE_NOT& operator=(S2S_GAME_SESSION_LEAVE_NOT&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S2S_GAME_SESSION_LEAVE_NOT& default_instance() {
    return *internal_default_instance();
  }
  static inline const S2S_GAME_SESSION_LEAVE_NOT* internal_default_instance() {
    return reinterpret_cast<const S2S_GAME_SESSION_LEAVE_NOT*>(
               &_S2S_GAME_SESSION_LEAVE_NOT_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(S2S_GAME_SESSION_LEAVE_NOT& a, S2S_GAME_SESSION_LEAVE_NOT& b) {
    a.Swap(&b);
  }
  inline void Swap(S2S_GAME_SESSION_LEAVE_NOT* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S2S_GAME_SESSION_LEAVE_NOT* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S2S_GAME_SESSION_LEAVE_NOT* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S2S_GAME_SESSION_LEAVE_NOT>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S2S_GAME_SESSION_LEAVE_NOT& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S2S_GAME_SESSION_LEAVE_NOT& from) {
    S2S_GAME_SESSION_LEAVE_NOT::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S2S_GAME_SESSION_LEAVE_NOT* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S2S_GAME_SESSION_LEAVE_NOT";
  }
  protected:
  explicit S2S_GAME_SESSION_LEAVE_NOT(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAccountIdFieldNumber = 1,
    kGatewaySessionIdFieldNumber = 2,
  };
  // uint64 accountId = 1;
  void clear_accountid();
  uint64_t accountid() const;
  void set_accountid(uint64_t value);
  private:
  uint64_t _internal_accountid() const;
  void _internal_set_accountid(uint64_t value);
  public:

  // uint64 gatewaySessionId = 2;
  void clear_gatewaysessionid();
  uint64_t gatewaysessionid() const;
  void set_gatewaysessionid(uint64_t value);
  private:
  uint64_t _internal_gatewaysessionid() const;
  void _internal_set_gatewaysessionid(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S2S_GAME_SESSION_LEAVE_NOT)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t accountid_;
    uint64_t gatewaysessionid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_GameSession_2eproto;
};
// -------------------------------------------------------------------

class S2S_GAME_SESSION_SYNC_ENTER_NOT final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S2S_GAME_SESSION_SYNC_ENTER_NOT) */ {
 public:
  inline S2S_GAME_SESSION_SYNC_ENTER_NOT() : S2S_GAME_SESSION_SYNC_ENTER_NOT(nullptr) {}
  ~S2S_GAME_SESSION_SYNC_ENTER_NOT() override;
  explicit PROTOBUF_CONSTEXPR S2S_GAME_SESSION_SYNC_ENTER_NOT(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S2S_GAME_SESSION_SYNC_ENTER_NOT(const S2S_GAME_SESSION_SYNC_ENTER_NOT& from);
  S2S_GAME_SESSION_SYNC_ENTER_NOT(S2S_GAME_SESSION_SYNC_ENTER_NOT&& from) noexcept
    : S2S_GAME_SESSION_SYNC_ENTER_NOT() {
    *this = ::std::move(from);
  }

  inline S2S_GAME_SESSION_SYNC_ENTER_NOT& operator=(const S2S_GAME_SESSION_SYNC_ENTER_NOT& from) {
    CopyFrom(from);
    return *this;
  }
  inline S2S_GAME_SESSION_SYNC_ENTER_NOT& operator=(S2S_GAME_SESSION_SYNC_ENTER_NOT&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S2S_GAME_SESSION_SYNC_ENTER_NOT& default_instance() {
    return *internal_default_instance();
  }
  static inline const S2S_GAME_SESSION_SYNC_ENTER_NOT* internal_default_instance() {
    return reinterpret_cast<const S2S_GAME_SESSION_SYNC_ENTER_NOT*>(
               &_S2S_GAME_SESSION_SYNC_ENTER_NOT_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(S2S_GAME_SESSION_SYNC_ENTER_NOT& a, S2S_GAME_SESSION_SYNC_ENTER_NOT& b) {
    a.Swap(&b);
  }
  inline void Swap(S2S_GAME_SESSION_SYNC_ENTER_NOT* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S2S_GAME_SESSION_SYNC_ENTER_NOT* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S2S_GAME_SESSION_SYNC_ENTER_NOT* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S2S_GAME_SESSION_SYNC_ENTER_NOT>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S2S_GAME_SESSION_SYNC_ENTER_NOT& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S2S_GAME_SESSION_SYNC_ENTER_NOT& from) {
    S2S_GAME_SESSION_SYNC_ENTER_NOT::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S2S_GAME_SESSION_SYNC_ENTER_NOT* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S2S_GAME_SESSION_SYNC_ENTER_NOT";
  }
  protected:
  explicit S2S_GAME_SESSION_SYNC_ENTER_NOT(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAccountIdFieldNumber = 1,
    kWorldServerIdFieldNumber = 2,
    kGatewayServerIdFieldNumber = 3,
  };
  // uint64 accountId = 1;
  void clear_accountid();
  uint64_t accountid() const;
  void set_accountid(uint64_t value);
  private:
  uint64_t _internal_accountid() const;
  void _internal_set_accountid(uint64_t value);
  public:

  // int32 worldServerId = 2;
  void clear_worldserverid();
  int32_t worldserverid() const;
  void set_worldserverid(int32_t value);
  private:
  int32_t _internal_worldserverid() const;
  void _internal_set_worldserverid(int32_t value);
  public:

  // int32 gatewayServerId = 3;
  void clear_gatewayserverid();
  int32_t gatewayserverid() const;
  void set_gatewayserverid(int32_t value);
  private:
  int32_t _internal_gatewayserverid() const;
  void _internal_set_gatewayserverid(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S2S_GAME_SESSION_SYNC_ENTER_NOT)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t accountid_;
    int32_t worldserverid_;
    int32_t gatewayserverid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_GameSession_2eproto;
};
// -------------------------------------------------------------------

class S2S_GAME_SESSION_SYNC_LEAVE_NOT final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S2S_GAME_SESSION_SYNC_LEAVE_NOT) */ {
 public:
  inline S2S_GAME_SESSION_SYNC_LEAVE_NOT() : S2S_GAME_SESSION_SYNC_LEAVE_NOT(nullptr) {}
  ~S2S_GAME_SESSION_SYNC_LEAVE_NOT() override;
  explicit PROTOBUF_CONSTEXPR S2S_GAME_SESSION_SYNC_LEAVE_NOT(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S2S_GAME_SESSION_SYNC_LEAVE_NOT(const S2S_GAME_SESSION_SYNC_LEAVE_NOT& from);
  S2S_GAME_SESSION_SYNC_LEAVE_NOT(S2S_GAME_SESSION_SYNC_LEAVE_NOT&& from) noexcept
    : S2S_GAME_SESSION_SYNC_LEAVE_NOT() {
    *this = ::std::move(from);
  }

  inline S2S_GAME_SESSION_SYNC_LEAVE_NOT& operator=(const S2S_GAME_SESSION_SYNC_LEAVE_NOT& from) {
    CopyFrom(from);
    return *this;
  }
  inline S2S_GAME_SESSION_SYNC_LEAVE_NOT& operator=(S2S_GAME_SESSION_SYNC_LEAVE_NOT&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S2S_GAME_SESSION_SYNC_LEAVE_NOT& default_instance() {
    return *internal_default_instance();
  }
  static inline const S2S_GAME_SESSION_SYNC_LEAVE_NOT* internal_default_instance() {
    return reinterpret_cast<const S2S_GAME_SESSION_SYNC_LEAVE_NOT*>(
               &_S2S_GAME_SESSION_SYNC_LEAVE_NOT_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(S2S_GAME_SESSION_SYNC_LEAVE_NOT& a, S2S_GAME_SESSION_SYNC_LEAVE_NOT& b) {
    a.Swap(&b);
  }
  inline void Swap(S2S_GAME_SESSION_SYNC_LEAVE_NOT* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S2S_GAME_SESSION_SYNC_LEAVE_NOT* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S2S_GAME_SESSION_SYNC_LEAVE_NOT* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S2S_GAME_SESSION_SYNC_LEAVE_NOT>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S2S_GAME_SESSION_SYNC_LEAVE_NOT& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S2S_GAME_SESSION_SYNC_LEAVE_NOT& from) {
    S2S_GAME_SESSION_SYNC_LEAVE_NOT::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S2S_GAME_SESSION_SYNC_LEAVE_NOT* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S2S_GAME_SESSION_SYNC_LEAVE_NOT";
  }
  protected:
  explicit S2S_GAME_SESSION_SYNC_LEAVE_NOT(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAccountIdFieldNumber = 1,
    kWorldServerIdFieldNumber = 2,
  };
  // uint64 accountId = 1;
  void clear_accountid();
  uint64_t accountid() const;
  void set_accountid(uint64_t value);
  private:
  uint64_t _internal_accountid() const;
  void _internal_set_accountid(uint64_t value);
  public:

  // int32 worldServerId = 2;
  void clear_worldserverid();
  int32_t worldserverid() const;
  void set_worldserverid(int32_t value);
  private:
  int32_t _internal_worldserverid() const;
  void _internal_set_worldserverid(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S2S_GAME_SESSION_SYNC_LEAVE_NOT)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t accountid_;
    int32_t worldserverid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_GameSession_2eproto;
};
// -------------------------------------------------------------------

class S2S_RELAY_TO_CLIENT_NOT final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S2S_RELAY_TO_CLIENT_NOT) */ {
 public:
  inline S2S_RELAY_TO_CLIENT_NOT() : S2S_RELAY_TO_CLIENT_NOT(nullptr) {}
  ~S2S_RELAY_TO_CLIENT_NOT() override;
  explicit PROTOBUF_CONSTEXPR S2S_RELAY_TO_CLIENT_NOT(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S2S_RELAY_TO_CLIENT_NOT(const S2S_RELAY_TO_CLIENT_NOT& from);
  S2S_RELAY_TO_CLIENT_NOT(S2S_RELAY_TO_CLIENT_NOT&& from) noexcept
    : S2S_RELAY_TO_CLIENT_NOT() {
    *this = ::std::move(from);
  }

  inline S2S_RELAY_TO_CLIENT_NOT& operator=(const S2S_RELAY_TO_CLIENT_NOT& from) {
    CopyFrom(from);
    return *this;
  }
  inline S2S_RELAY_TO_CLIENT_NOT& operator=(S2S_RELAY_TO_CLIENT_NOT&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S2S_RELAY_TO_CLIENT_NOT& default_instance() {
    return *internal_default_instance();
  }
  static inline const S2S_RELAY_TO_CLIENT_NOT* internal_default_instance() {
    return reinterpret_cast<const S2S_RELAY_TO_CLIENT_NOT*>(
               &_S2S_RELAY_TO_CLIENT_NOT_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(S2S_RELAY_TO_CLIENT_NOT& a, S2S_RELAY_TO_CLIENT_NOT& b) {
    a.Swap(&b);
  }
  inline void Swap(S2S_RELAY_TO_CLIENT_NOT* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S2S_RELAY_TO_CLIENT_NOT* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S2S_RELAY_TO_CLIENT_NOT* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S2S_RELAY_TO_CLIENT_NOT>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S2S_RELAY_TO_CLIENT_NOT& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S2S_RELAY_TO_CLIENT_NOT& from) {
    S2S_RELAY_TO_CLIENT_NOT::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S2S_RELAY_TO_CLIENT_NOT* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S2S_RELAY_TO_CLIENT_NOT";
  }
  protected:
  explicit S2S_RELAY_TO_CLIENT_NOT(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPayloadFieldNumber = 2,
    kGatewaySessionIdFieldNumber = 1,
  };
  // bytes payload = 2;
  void clear_payload();
  const std::string& payload() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_payload(ArgT0&& arg0, ArgT... args);
  std::string* mutable_payload();
  PROTOBUF_NODISCARD std::string* release_payload();
  void set_allocated_payload(std::string* payload);
  private:
  const std::string& _internal_payload() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_payload(const std::string& value);
  std::string* _internal_mutable_payload();
  public:

  // uint64 gatewaySessionId = 1;
  void clear_gatewaysessionid();
  uint64_t gatewaysessionid() const;
  void set_gatewaysessionid(uint64_t value);
  private:
  uint64_t _internal_gatewaysessionid() const;
  void _internal_set_gatewaysessionid(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S2S_RELAY_TO_CLIENT_NOT)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr payload_;
    uint64_t gatewaysessionid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_GameSession_2eproto;
};
// -------------------------------------------------------------------

class S2S_RELAY_TO_WORLD_NOT final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S2S_RELAY_TO_WORLD_NOT) */ {
 public:
  inline S2S_RELAY_TO_WORLD_NOT() : S2S_RELAY_TO_WORLD_NOT(nullptr) {}
  ~S2S_RELAY_TO_WORLD_NOT() override;
  explicit PROTOBUF_CONSTEXPR S2S_RELAY_TO_WORLD_NOT(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S2S_RELAY_TO_WORLD_NOT(const S2S_RELAY_TO_WORLD_NOT& from);
  S2S_RELAY_TO_WORLD_NOT(S2S_RELAY_TO_WORLD_NOT&& from) noexcept
    : S2S_RELAY_TO_WORLD_NOT() {
    *this = ::std::move(from);
  }

  inline S2S_RELAY_TO_WORLD_NOT& operator=(const S2S_RELAY_TO_WORLD_NOT& from) {
    CopyFrom(from);
    return *this;
  }
  inline S2S_RELAY_TO_WORLD_NOT& operator=(S2S_RELAY_TO_WORLD_NOT&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S2S_RELAY_TO_WORLD_NOT& default_instance() {
    return *internal_default_instance();
  }
  static inline const S2S_RELAY_TO_WORLD_NOT* internal_default_instance() {
    return reinterpret_cast<const S2S_RELAY_TO_WORLD_NOT*>(
               &_S2S_RELAY_TO_WORLD_NOT_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(S2S_RELAY_TO_WORLD_NOT& a, S2S_RELAY_TO_WORLD_NOT& b) {
    a.Swap(&b);
  }
  inline void Swap(S2S_RELAY_TO_WORLD_NOT* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S2S_RELAY_TO_WORLD_NOT* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S2S_RELAY_TO_WORLD_NOT* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S2S_RELAY_TO_WORLD_NOT>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S2S_RELAY_TO_WORLD_NOT& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S2S_RELAY_TO_WORLD_NOT& from) {
    S2S_RELAY_TO_WORLD_NOT::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S2S_RELAY_TO_WORLD_NOT* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S2S_RELAY_TO_WORLD_NOT";
  }
  protected:
  explicit S2S_RELAY_TO_WORLD_NOT(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPayloadFieldNumber = 2,
    kAccountIdFieldNumber = 1,
  };
  // bytes payload = 2;
  void clear_payload();
  const std::string& payload() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_payload(ArgT0&& arg0, ArgT... args);
  std::string* mutable_payload();
  PROTOBUF_NODISCARD std::string* release_payload();
  void set_allocated_payload(std::string* payload);
  private:
  const std::string& _internal_payload() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_payload(const std::string& value);
  std::string* _internal_mutable_payload();
  public:

  // uint64 accountId = 1;
  void clear_accountid();
  uint64_t accountid() const;
  void set_accountid(uint64_t value);
  private:
  uint64_t _internal_accountid() const;
  void _internal_set_accountid(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S2S_RELAY_TO_WORLD_NOT)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr payload_;
    uint64_t accountid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_GameSession_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// S2S_GAME_SESSION_ENTER_NOT

// uint64 accountId = 1;
inline void S2S_GAME_SESSION_ENTER_NOT::clear_accountid() {
  _impl_.accountid_ = uint64_t{0u};
}
inline uint64_t S2S_GAME_SESSION_ENTER_NOT::_internal_accountid() const {
  return _impl_.accountid_;
}
inline uint64_t S2S_GAME_SESSION_ENTER_NOT::accountid() const {
  // @@protoc_insertion_point(field_get:Protocol.S2S_GAME_SESSION_ENTER_NOT.accountId)
  return _internal_accountid();
}
inline void S2S_GAME_SESSION_ENTER_NOT::_internal_set_accountid(uint64_t value) {
  
  _impl_.accountid_ = value;
}
inline void S2S_GAME_SESSION_ENTER_NOT::set_accountid(uint64_t value) {
  _internal_set_accountid(value);
  // @@protoc_insertion_point(field_set:Protocol.S2S_GAME_SESSION_ENTER_NOT.accountId)
}

// uint64 gatewaySessionId = 2;
inline void S2S_GAME_SESSION_ENTER_NOT::clear_gatewaysessionid() {
  _impl_.gatewaysessionid_ = uint64_t{0u};
}
inline uint64_t S2S_GAME_SESSION_ENTER_NOT::_internal_gatewaysessionid() const {
  return _impl_.gatewaysessionid_;
}
inline uint64_t S2S_GAME_SESSION_ENTER_NOT::gatewaysessionid() const {
  // @@protoc_insertion_point(field_get:Protocol.S2S_GAME_SESSION_ENTER_NOT.gatewaySessionId)
  return _internal_gatewaysessionid();
}
inline void S2S_GAME_SESSION_ENTER_NOT::_internal_set_gatewaysessionid(uint64_t value) {
  
  _impl_.gatewaysessionid_ = value;
}
inline void S2S_GAME_SESSION_ENTER_NOT::set_gatewaysessionid(uint64_t value) {
  _internal_set_gatewaysessionid(value);
  // @@protoc_insertion_point(field_set:Protocol.S2S_GAME_SESSION_ENTER_NOT.gatewaySessionId)
}

// int32 gatewayServerId = 3;
inline void S2S_GAME_SESSION_ENTER_NOT::clear_gatewayserverid() {
  _impl_.gatewayserverid_ = 0;
}
inline int32_t S2S_GAME_SESSION_ENTER_NOT::_internal_gatewayserverid() const {
  return _impl_.gatewayserverid_;
}
inline int32_t S2S_GAME_SESSION_ENTER_NOT::gatewayserverid() const {
  // @@protoc_insertion_point(field_get:Protocol.S2S_GAME_SESSION_ENTER_NOT.gatewayServerId)
  return _internal_gatewayserverid();
}
inline void S2S_GAME_SESSION_ENTER_NOT::_internal_set_gatewayserverid(int32_t value) {
  
  _impl_.gatewayserverid_ = value;
}
inline void S2S_GAME_SESSION_ENTER_NOT::set_gatewayserverid(int32_t value) {
  _internal_set_gatewayserverid(value);
  // @@protoc_insertion_point(field_set:Protocol.S2S_GAME_SESSION_ENTER_NOT.gatewayServerId)
}

// -------------------------------------------------------------------

// S2S_GAME_SESSION_ENTER_RES

// uint64 accountId = 1;
inline void S2S_GAME_SESSION_ENTER_RES::clear_accountid() {
  _impl_.accountid_ = uint64_t{0u};
}
inline uint64_t S2S_GAME_SESSION_ENTER_RES::_internal_accountid() const {
  return _impl_.accountid_;
}
inline uint64_t S2S_GAME_SESSION_ENTER_RES::accountid() const {
  // @@protoc_insertion_point(field_get:Protocol.S2S_GAME_SESSION_ENTER_RES.accountId)
  return _internal_accountid();
}
inline void S2S_GAME_SESSION_ENTER_RES::_internal_set_accountid(uint64_t value) {
  
  _impl_.accountid_ = value;
}
inline void S2S_GAME_SESSION_ENTER_RES::set_accountid(uint64_t value) {
  _internal_set_accountid(value);
  // @@protoc_insertion_point(field_set:Protocol.S2S_GAME_SESSION_ENTER_RES.accountId)
}

// .Protocol.eGameSessionResult result = 2;
inline void S2S_GAME_SESSION_ENTER_RES::clear_result() {
  _impl_.result_ = 0;
}
inline ::Protocol::eGameSessionResult S2S_GAME_SESSION_ENTER_RES::_internal_result() const {
  return static_cast< ::Protocol::eGameSessionResult >(_impl_.result_);
}
inline ::Protocol::eGameSessionResult S2S_GAME_SESSION_ENTER_RES::result() const {
  // @@protoc_insertion_point(field_get:Protocol.S2S_GAME_SESSION_ENTER_RES.result)
  return _internal_result();
}
inline void S2S_GAME_SESSION_ENTER_RES::_internal_set_result(::Protocol::eGameSessionResult value) {
  
  _impl_.result_ = value;
}
inline void S2S_GAME_SESSION_ENTER_RES::set_result(::Protocol::eGameSessionResult value) {
  _internal_set_result(value);
  // @@protoc_insertion_point(field_set:Protocol.S2S_GAME_SESSION_ENTER_RES.result)
}

// -------------------------------------------------------------------

// S2S_GAME_SESSION_LEAVE_NOT

// uint64 accountId = 1;
inline void S2S_GAME_SESSION_LEAVE_NOT::clear_accountid() {
  _impl_.accountid_ = uint64_t{0u};
}
inline uint64_t S2S_GAME_SESSION_LEAVE_NOT::_internal_accountid() const {
  return _impl_.accountid_;
}
inline uint64_t S2S_GAME_SESSION_LEAVE_NOT::accountid() const {
  // @@protoc_insertion_point(field_get:Protocol.S2S_GAME_SESSION_LEAVE_NOT.accountId)
  return _internal_accountid();
}
inline void S2S_GAME_SESSION_LEAVE_NOT::_internal_set_accountid(uint64_t value) {
  
  _impl_.accountid_ = value;
}
inline void S2S_GAME_SESSION_LEAVE_NOT::set_accountid(uint64_t value) {
  _internal_set_accountid(value);
  // @@protoc_insertion_point(field_set:Protocol.S2S_GAME_SESSION_LEAVE_NOT.accountId)
}

// uint64 gatewaySessionId = 2;
inline void S2S_GAME_SESSION_LEAVE_NOT::clear_gatewaysessionid() {
  _impl_.gatewaysessionid_ = uint64_t{0u};
}
inline uint64_t S2S_GAME_SESSION_LEAVE_NOT::_internal_gatewaysessionid() const {
  return _impl_.gatewaysessionid_;
}
inline uint64_t S2S_GAME_SESSION_LEAVE_NOT::gatewaysessionid() const {
  // @@protoc_insertion_point(field_get:Protocol.S2S_GAME_SESSION_LEAVE_NOT.gatewaySessionId)
  return _internal_gatewaysessionid();
}
inline void S2S_GAME_SESSION_LEAVE_NOT::_internal_set_gatewaysessionid(uint64_t value) {
  
  _impl_.gatewaysessionid_ = value;
}
inline void S2S_GAME_SESSION_LEAVE_NOT::set_gatewaysessionid(uint64_t value) {
  _internal_set_gatewaysessionid(value);
  // @@protoc_insertion_point(field_set:Protocol.S2S_GAME_SESSION_LEAVE_NOT.gatewaySessionId)
}

// -------------------------------------------------------------------

// S2S_GAME_SESSION_SYNC_ENTER_NOT

// uint64 accountId = 1;
inline void S2S_GAME_SESSION_SYNC_ENTER_NOT::clear_accountid() {
  _impl_.accountid_ = uint64_t{0u};
}
inline uint64_t S2S_GAME_SESSION_SYNC_ENTER_NOT::_internal_accountid() const {
  return _impl_.accountid_;
}
inline uint64_t S2S_GAME_SESSION_SYNC_ENTER_NOT::accountid() const {
  // @@protoc_insertion_point(field_get:Protocol.S2S_GAME_SESSION_SYNC_ENTER_NOT.accountId)
  return _internal_accountid();
}
inline void S2S_GAME_SESSION_SYNC_ENTER_NOT::_internal_set_accountid(uint64_t value) {
  
  _impl_.accountid_ = value;
}
inline void S2S_GAME_SESSION_SYNC_ENTER_NOT::set_accountid(uint64_t value) {
  _internal_set_accountid(value);
  // @@protoc_insertion_point(field_set:Protocol.S2S_GAME_SESSION_SYNC_ENTER_NOT.accountId)
}

// int32 worldServerId = 2;
inline void S2S_GAME_SESSION_SYNC_ENTER_NOT::clear_worldserverid() {
  _impl_.worldserverid_ = 0;
}
inline int32_t S2S_GAME_SESSION_SYNC_ENTER_NOT::_internal_worldserverid() const {
  return _impl_.worldserverid_;
}
inline int32_t S2S_GAME_SESSION_SYNC_ENTER_NOT::worldserverid() const {
  // @@protoc_insertion_point(field_get:Protocol.S2S_GAME_SESSION_SYNC_ENTER_NOT.worldServerId)
  return _internal_worldserverid();
}
inline void S2S_GAME_SESSION_SYNC_ENTER_NOT::_internal_set_worldserverid(int32_t value) {
  
  _impl_.worldserverid_ = value;
}
inline void S2S_GAME_SESSION_SYNC_ENTER_NOT::set_worldserverid(int32_t value) {
  _internal_set_worldserverid(value);
  // @@protoc_insertion_point(field_set:Protocol.S2S_GAME_SESSION_SYNC_ENTER_NOT.worldServerId)
}

// int32 gatewayServerId = 3;
inline void S2S_GAME_SESSION_SYNC_ENTER_NOT::clear_gatewayserverid() {
  _impl_.gatewayserverid_ = 0;
}
inline int32_t S2S_GAME_SESSION_SYNC_ENTER_NOT::_internal_gatewayserverid() const {
  return _impl_.gatewayserverid_;
}
inline int32_t S2S_GAME_SESSION_SYNC_ENTER_NOT::gatewayserverid() const {
  // @@protoc_insertion_point(field_get:Protocol.S2S_GAME_SESSION_SYNC_ENTER_NOT.gatewayServerId)
  return _internal_gatewayserverid();
}
inline void S2S_GAME_SESSION_SYNC_ENTER_NOT::_internal_set_gatewayserverid(int32_t value) {
  
  _impl_.gatewayserverid_ = value;
}
inline void S2S_GAME_SESSION_SYNC_ENTER_NOT::set_gatewayserverid(int32_t value) {
  _internal_set_gatewayserverid(value);
  // @@protoc_insertion_point(field_set:Protocol.S2S_GAME_SESSION_SYNC_ENTER_NOT.gatewayServerId)
}

// -------------------------------------------------------------------

// S2S_GAME_SESSION_SYNC_LEAVE_NOT

// uint64 accountId = 1;
inline void S2S_GAME_SESSION_SYNC_LEAVE_NOT::clear_accountid() {
  _impl_.accountid_ = uint64_t{0u};
}
inline uint64_t S2S_GAME_SESSION_SYNC_LEAVE_NOT::_internal_accountid() const {
  return _impl_.accountid_;
}
inline uint64_t S2S_GAME_SESSION_SYNC_LEAVE_NOT::accountid() const {
  // @@protoc_insertion_point(field_get:Protocol.S2S_GAME_SESSION_SYNC_LEAVE_NOT.accountId)
  return _internal_accountid();
}
inline void S2S_GAME_SESSION_SYNC_LEAVE_NOT::_internal_set_accountid(uint64_t value) {
  
  _impl_.accountid_ = value;
}
inline void S2S_GAME_SESSION_SYNC_LEAVE_NOT::set_accountid(uint64_t value) {
  _internal_set_accountid(value);
  // @@protoc_insertion_point(field_set:Protocol.S2S_GAME_SESSION_SYNC_LEAVE_NOT.accountId)
}

// int32 worldServerId = 2;
inline void S2S_GAME_SESSION_SYNC_LEAVE_NOT::clear_worldserverid() {
  _impl_.worldserverid_ = 0;
}
inline int32_t S2S_GAME_SESSION_SYNC_LEAVE_NOT::_internal_worldserverid() const {
  return _impl_.worldserverid_;
}
inline int32_t S2S_GAME_SESSION_SYNC_LEAVE_NOT::worldserverid() const {
  // @@protoc_insertion_point(field_get:Protocol.S2S_GAME_SESSION_SYNC_LEAVE_NOT.worldServerId)
  return _internal_worldserverid();
}
inline void S2S_GAME_SESSION_SYNC_LEAVE_NOT::_internal_set_worldserverid(int32_t value) {
  
  _impl_.worldserverid_ = value;
}
inline void S2S_GAME_SESSION_SYNC_LEAVE_NOT::set_worldserverid(int32_t value) {
  _internal_set_worldserverid(value);
  // @@protoc_insertion_point(field_set:Protocol.S2S_GAME_SESSION_SYNC_LEAVE_NOT.worldServerId)
}

// -------------------------------------------------------------------

// S2S_RELAY_TO_CLIENT_NOT

// uint64 gatewaySessionId = 1;
inline void S2S_RELAY_TO_CLIENT_NOT::clear_gatewaysessionid() {
  _impl_.gatewaysessionid_ = uint64_t{0u};
}
inline uint64_t S2S_RELAY_TO_CLIENT_NOT::_internal_gatewaysessionid() const {
  return _impl_.gatewaysessionid_;
}
inline uint64_t S2S_RELAY_TO_CLIENT_NOT::gatewaysessionid() const {
  // @@protoc_insertion_point(field_get:Protocol.S2S_RELAY_TO_CLIENT_NOT.gatewaySessionId)
  return _internal_gatewaysessionid();
}
inline void S2S_RELAY_TO_CLIENT_NOT::_internal_set_gatewaysessionid(uint64_t value) {
  
  _impl_.gatewaysessionid_ = value;
}
inline void S2S_RELAY_TO_CLIENT_NOT::set_gatewaysessionid(uint64_t value) {
  _internal_set_gatewaysessionid(value);
  // @@protoc_insertion_point(field_set:Protocol.S2S_RELAY_TO_CLIENT_NOT.gatewaySessionId)
}

// bytes payload = 2;
inline void S2S_RELAY_TO_CLIENT_NOT::clear_payload() {
  _impl_.payload_.ClearToEmpty();
}
inline const std::string& S2S_RELAY_TO_CLIENT_NOT::payload() const {
  // @@protoc_insertion_point(field_get:Protocol.S2S_RELAY_TO_CLIENT_NOT.payload)
  return _internal_payload();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void S2S_RELAY_TO_CLIENT_NOT::set_payload(ArgT0&& arg0, ArgT... args) {
 
 _impl_.payload_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.S2S_RELAY_TO_CLIENT_NOT.payload)
}
inline std::string* S2S_RELAY_TO_CLIENT_NOT::mutable_payload() {
  std::string* _s = _internal_mutable_payload();
  // @@protoc_insertion_point(field_mutable:Protocol.S2S_RELAY_TO_CLIENT_NOT.payload)
  return _s;
}
inline const std::string& S2S_RELAY_TO_CLIENT_NOT::_internal_payload() const {
  return _impl_.payload_.Get();
}
inline void S2S_RELAY_TO_CLIENT_NOT::_internal_set_payload(const std::string& value) {
  
  _impl_.payload_.Set(value, GetArenaForAllocation());
}
inline std::string* S2S_RELAY_TO_CLIENT_NOT::_internal_mutable_payload() {
  
  return _impl_.payload_.Mutable(GetArenaForAllocation());
}
inline std::string* S2S_RELAY_TO_CLIENT_NOT::release_payload() {
  // @@protoc_insertion_point(field_release:Protocol.S2S_RELAY_TO_CLIENT_NOT.payload)
  return _impl_.payload_.Release();
}
inline void S2S_RELAY_TO_CLIENT_NOT::set_allocated_payload(std::string* payload) {
  if (payload != nullptr) {
    
  } else {
    
  }
  _impl_.payload_.SetAllocated(payload, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.payload_.IsDefault()) {
    _impl_.payload_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.S2S_RELAY_TO_CLIENT_NOT.payload)
}

// -------------------------------------------------------------------

// S2S_RELAY_TO_WORLD_NOT

// uint64 accountId = 1;
inline void S2S_RELAY_TO_WORLD_NOT::clear_accountid() {
  _impl_.accountid_ = uint64_t{0u};
}
inline uint64_t S2S_RELAY_TO_WORLD_NOT::_internal_accountid() const {
  return _impl_.accountid_;
}
inline uint64_t S2S_RELAY_TO_WORLD_NOT::accountid() const {
  // @@protoc_insertion_point(field_get:Protocol.S2S_RELAY_TO_WORLD_NOT.accountId)
  return _internal_accountid();
}
inline void S2S_RELAY_TO_WORLD_NOT::_internal_set_accountid(uint64_t value) {
  
  _impl_.accountid_ = value;
}
inline void S2S_RELAY_TO_WORLD_NOT::set_accountid(uint64_t value) {
  _internal_set_accountid(value);
  // @@protoc_insertion_point(field_set:Protocol.S2S_RELAY_TO_WORLD_NOT.accountId)
}

// bytes payload = 2;
inline void S2S_RELAY_TO_WORLD_NOT::clear_payload() {
  _impl_.payload_.ClearToEmpty();
}
inline const std::string& S2S_RELAY_TO_WORLD_NOT::payload() const {
  // @@protoc_insertion_point(field_get:Protocol.S2S_RELAY_TO_WORLD_NOT.payload)
  return _internal_payload();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void S2S_RELAY_TO_WORLD_NOT::set_payload(ArgT0&& arg0, ArgT... args) {
 
 _impl_.payload_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.S2S_RELAY_TO_WORLD_NOT.payload)
}
inline std::string* S2S_RELAY_TO_WORLD_NOT::mutable_payload() {
  std::string* _s = _internal_mutable_payload();
  // @@protoc_insertion_point(field_mutable:Protocol.S2S_RELAY_TO_WORLD_NOT.payload)
  return _s;
}
inline const std::string& S2S_RELAY_TO_WORLD_NOT::_internal_payload() const {
  return _impl_.payload_.Get();
}
inline void S2S_RELAY_TO_WORLD_NOT::_internal_set_payload(const std::string& value) {
  
  _impl_.payload_.Set(value, GetArenaForAllocation());
}
inline std::string* S2S_RELAY_TO_WORLD_NOT::_internal_mutable_payload() {
  
  return _impl_.payload_.Mutable(GetArenaForAllocation());
}
inline std::string* S2S_RELAY_TO_WORLD_NOT::release_payload() {
  // @@protoc_insertion_point(field_release:Protocol.S2S_RELAY_TO_WORLD_NOT.payload)
  return _impl_.payload_.Release();
}
inline void S2S_RELAY_TO_WORLD_NOT::set_allocated_payload(std::string* payload) {
  if (payload != nullptr) {
    
  } else {
    
  }
  _impl_.payload_.SetAllocated(payload, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.payload_.IsDefault()) {
    _impl_.payload_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.S2S_RELAY_TO_WORLD_NOT.payload)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_GameSession_2eproto
