// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Heartbeat.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Heartbeat_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Heartbeat_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "PacketOption.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Heartbeat_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Heartbeat_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Heartbeat_2eproto;
namespace Protocol {
class C2S_HEARTBEAT_REQ;
struct C2S_HEARTBEAT_REQDefaultTypeInternal;
extern C2S_HEARTBEAT_REQDefaultTypeInternal _C2S_HEARTBEAT_REQ_default_instance_;
class S2C_HEARTBEAT_RES;
struct S2C_HEARTBEAT_RESDefaultTypeInternal;
extern S2C_HEARTBEAT_RESDefaultTypeInternal _S2C_HEARTBEAT_RES_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::C2S_HEARTBEAT_REQ* Arena::CreateMaybeMessage<::Protocol::C2S_HEARTBEAT_REQ>(Arena*);
template<> ::Protocol::S2C_HEARTBEAT_RES* Arena::CreateMaybeMessage<::Protocol::S2C_HEARTBEAT_RES>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class C2S_HEARTBEAT_REQ final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.C2S_HEARTBEAT_REQ) */ {
 public:
  inline C2S_HEARTBEAT_REQ() : C2S_HEARTBEAT_REQ(nullptr) {}
  ~C2S_HEARTBEAT_REQ() override;
  explicit PROTOBUF_CONSTEXPR C2S_HEARTBEAT_REQ(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C2S_HEARTBEAT_REQ(const C2S_HEARTBEAT_REQ& from);
  C2S_HEARTBEAT_REQ(C2S_HEARTBEAT_REQ&& from) noexcept
    : C2S_HEARTBEAT_REQ() {
    *this = ::std::move(from);
  }

  inline C2S_HEARTBEAT_REQ& operator=(const C2S_HEARTBEAT_REQ& from) {
    CopyFrom(from);
    return *this;
  }
  inline C2S_HEARTBEAT_REQ& operator=(C2S_HEARTBEAT_REQ&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C2S_HEARTBEAT_REQ& default_instance() {
    return *internal_default_instance();
  }
  static inline const C2S_HEARTBEAT_REQ* internal_default_instance() {
    return reinterpret_cast<const C2S_HEARTBEAT_REQ*>(
               &_C2S_HEARTBEAT_REQ_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(C2S_HEARTBEAT_REQ& a, C2S_HEARTBEAT_REQ& b) {
    a.Swap(&b);
  }
  inline void Swap(C2S_HEARTBEAT_REQ* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C2S_HEARTBEAT_REQ* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C2S_HEARTBEAT_REQ* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<C2S_HEARTBEAT_REQ>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const C2S_HEARTBEAT_REQ& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const C2S_HEARTBEAT_REQ& from) {
    C2S_HEARTBEAT_REQ::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C2S_HEARTBEAT_REQ* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.C2S_HEARTBEAT_REQ";
  }
  protected:
  explicit C2S_HEARTBEAT_REQ(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kClientTimestampFieldNumber = 1,
  };
  // int64 clientTimestamp = 1;
  void clear_clienttimestamp();
  int64_t clienttimestamp() const;
  void set_clienttimestamp(int64_t value);
  private:
  int64_t _internal_clienttimestamp() const;
  void _internal_set_clienttimestamp(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.C2S_HEARTBEAT_REQ)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t clienttimestamp_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Heartbeat_2eproto;
};
// -------------------------------------------------------------------

class S2C_HEARTBEAT_RES final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S2C_HEARTBEAT_RES) */ {
 public:
  inline S2C_HEARTBEAT_RES() : S2C_HEARTBEAT_RES(nullptr) {}
  ~S2C_HEARTBEAT_RES() override;
  explicit PROTOBUF_CONSTEXPR S2C_HEARTBEAT_RES(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S2C_HEARTBEAT_RES(const S2C_HEARTBEAT_RES& from);
  S2C_HEARTBEAT_RES(S2C_HEARTBEAT_RES&& from) noexcept
    : S2C_HEARTBEAT_RES() {
    *this = ::std::move(from);
  }

  inline S2C_HEARTBEAT_RES& operator=(const S2C_HEARTBEAT_RES& from) {
    CopyFrom(from);
    return *this;
  }
  inline S2C_HEARTBEAT_RES& operator=(S2C_HEARTBEAT_RES&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S2C_HEARTBEAT_RES& default_instance() {
    return *internal_default_instance();
  }
  static inline const S2C_HEARTBEAT_RES* internal_default_instance() {
    return reinterpret_cast<const S2C_HEARTBEAT_RES*>(
               &_S2C_HEARTBEAT_RES_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(S2C_HEARTBEAT_RES& a, S2C_HEARTBEAT_RES& b) {
    a.Swap(&b);
  }
  inline void Swap(S2C_HEARTBEAT_RES* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S2C_HEARTBEAT_RES* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S2C_HEARTBEAT_RES* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S2C_HEARTBEAT_RES>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S2C_HEARTBEAT_RES& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S2C_HEARTBEAT_RES& from) {
    S2C_HEARTBEAT_RES::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S2C_HEARTBEAT_RES* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S2C_HEARTBEAT_RES";
  }
  protected:
  explicit S2C_HEARTBEAT_RES(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kClientTimestampFieldNumber = 1,
    kServerTimestampFieldNumber = 2,
  };
  // int64 clientTimestamp = 1;
  void clear_clienttimestamp();
  int64_t clienttimestamp() const;
  void set_clienttimestamp(int64_t value);
  private:
  int64_t _internal_clienttimestamp() const;
  void _internal_set_clienttimestamp(int64_t value);
  public:

  // int64 serverTimestamp = 2;
  void clear_servertimestamp();
  int64_t servertimestamp() const;
  void set_servertimestamp(int64_t value);
  private:
  int64_t _internal_servertimestamp() const;
  void _internal_set_servertimestamp(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S2C_HEARTBEAT_RES)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t clienttimestamp_;
    int64_t servertimestamp_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Heartbeat_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// C2S_HEARTBEAT_REQ

// int64 clientTimestamp = 1;
inline void C2S_HEARTBEAT_REQ::clear_clienttimestamp() {
  _impl_.clienttimestamp_ = int64_t{0};
}
inline int64_t C2S_HEARTBEAT_REQ::_internal_clienttimestamp() const {
  return _impl_.clienttimestamp_;
}
inline int64_t C2S_HEARTBEAT_REQ::clienttimestamp() const {
  // @@protoc_insertion_point(field_get:Protocol.C2S_HEARTBEAT_REQ.clientTimestamp)
  return _internal_clienttimestamp();
}
inline void C2S_HEARTBEAT_REQ::_internal_set_clienttimestamp(int64_t value) {
  
  _impl_.clienttimestamp_ = value;
}
inline void C2S_HEARTBEAT_REQ::set_clienttimestamp(int64_t value) {
  _internal_set_clienttimestamp(value);
  // @@protoc_insertion_point(field_set:Protocol.C2S_HEARTBEAT_REQ.clientTimestamp)
}

// -------------------------------------------------------------------

// S2C_HEARTBEAT_RES

// int64 clientTimestamp = 1;
inline void S2C_HEARTBEAT_RES::clear_clienttimestamp() {
  _impl_.clienttimestamp_ = int64_t{0};
}
inline int64_t S2C_HEARTBEAT_RES::_internal_clienttimestamp() const {
  return _impl_.clienttimestamp_;
}
inline int64_t S2C_HEARTBEAT_RES::clienttimestamp() const {
  // @@protoc_insertion_point(field_get:Protocol.S2C_HEARTBEAT_RES.clientTimestamp)
  return _internal_clienttimestamp();
}
inline void S2C_HEARTBEAT_RES::_internal_set_clienttimestamp(int64_t value) {
  
  _impl_.clienttimestamp_ = value;
}
inline void S2C_HEARTBEAT_RES::set_clienttimestamp(int64_t value) {
  _internal_set_clienttimestamp(value);
  // @@protoc_insertion_point(field_set:Protocol.S2C_HEARTBEAT_RES.clientTimestamp)
}

// int64 serverTimestamp = 2;
inline void S2C_HEARTBEAT_RES::clear_servertimestamp() {
  _impl_.servertimestamp_ = int64_t{0};
}
inline int64_t S2C_HEARTBEAT_RES::_internal_servertimestamp() const {
  return _impl_.servertimestamp_;
}
inline int64_t S2C_HEARTBEAT_RES::servertimestamp() const {
  // @@protoc_insertion_point(field_get:Protocol.S2C_HEARTBEAT_RES.serverTimestamp)
  return _internal_servertimestamp();
}
inline void S2C_HEARTBEAT_RES::_internal_set_servertimestamp(int64_t value) {
  
  _impl_.servertimestamp_ = value;
}
inline void S2C_HEARTBEAT_RES::set_servertimestamp(int64_t value) {
  _internal_set_servertimestamp(value);
  // @@protoc_insertion_point(field_set:Protocol.S2C_HEARTBEAT_RES.serverTimestamp)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Heartbeat_2eproto
