// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Heartbeat.proto

#include "Heartbeat.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Protocol {
PROTOBUF_CONSTEXPR C2S_HEARTBEAT_NOT::C2S_HEARTBEAT_NOT(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.clienttimestamp_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct C2S_HEARTBEAT_NOTDefaultTypeInternal {
  PROTOBUF_CONSTEXPR C2S_HEARTBEAT_NOTDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~C2S_HEARTBEAT_NOTDefaultTypeInternal() {}
  union {
    C2S_HEARTBEAT_NOT _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 C2S_HEARTBEAT_NOTDefaultTypeInternal _C2S_HEARTBEAT_NOT_default_instance_;
}  // namespace Protocol
static ::_pb::Metadata file_level_metadata_Heartbeat_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_Heartbeat_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Heartbeat_2eproto = nullptr;

const uint32_t TableStruct_Heartbeat_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::C2S_HEARTBEAT_NOT, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::Protocol::C2S_HEARTBEAT_NOT, _impl_.clienttimestamp_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::Protocol::C2S_HEARTBEAT_NOT)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::Protocol::_C2S_HEARTBEAT_NOT_default_instance_._instance,
};

const char descriptor_table_protodef_Heartbeat_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\017Heartbeat.proto\022\010Protocol\032\022PacketOptio"
  "n.proto\"6\n\021C2S_HEARTBEAT_NOT\022\027\n\017clientTi"
  "mestamp\030\001 \001(\003:\010\240\265\030\001\250\265\030\004B\036\210\265\030\003\222\265\030\026Heartbe"
  "atPacketHandlerb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_Heartbeat_2eproto_deps[1] = {
  &::descriptor_table_PacketOption_2eproto,
};
static ::_pbi::once_flag descriptor_table_Heartbeat_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Heartbeat_2eproto = {
    false, false, 143, descriptor_table_protodef_Heartbeat_2eproto,
    "Heartbeat.proto",
    &descriptor_table_Heartbeat_2eproto_once, descriptor_table_Heartbeat_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_Heartbeat_2eproto::offsets,
    file_level_metadata_Heartbeat_2eproto, file_level_enum_descriptors_Heartbeat_2eproto,
    file_level_service_descriptors_Heartbeat_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Heartbeat_2eproto_getter() {
  return &descriptor_table_Heartbeat_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Heartbeat_2eproto(&descriptor_table_Heartbeat_2eproto);
namespace Protocol {

// ===================================================================

class C2S_HEARTBEAT_NOT::_Internal {
 public:
};

C2S_HEARTBEAT_NOT::C2S_HEARTBEAT_NOT(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:Protocol.C2S_HEARTBEAT_NOT)
}
C2S_HEARTBEAT_NOT::C2S_HEARTBEAT_NOT(const C2S_HEARTBEAT_NOT& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  C2S_HEARTBEAT_NOT* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.clienttimestamp_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.clienttimestamp_ = from._impl_.clienttimestamp_;
  // @@protoc_insertion_point(copy_constructor:Protocol.C2S_HEARTBEAT_NOT)
}

inline void C2S_HEARTBEAT_NOT::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.clienttimestamp_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

C2S_HEARTBEAT_NOT::~C2S_HEARTBEAT_NOT() {
  // @@protoc_insertion_point(destructor:Protocol.C2S_HEARTBEAT_NOT)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void C2S_HEARTBEAT_NOT::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void C2S_HEARTBEAT_NOT::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void C2S_HEARTBEAT_NOT::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.C2S_HEARTBEAT_NOT)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.clienttimestamp_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* C2S_HEARTBEAT_NOT::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 clientTimestamp = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.clienttimestamp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* C2S_HEARTBEAT_NOT::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.C2S_HEARTBEAT_NOT)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 clientTimestamp = 1;
  if (this->_internal_clienttimestamp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_clienttimestamp(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.C2S_HEARTBEAT_NOT)
  return target;
}

size_t C2S_HEARTBEAT_NOT::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.C2S_HEARTBEAT_NOT)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 clientTimestamp = 1;
  if (this->_internal_clienttimestamp() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_clienttimestamp());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData C2S_HEARTBEAT_NOT::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    C2S_HEARTBEAT_NOT::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*C2S_HEARTBEAT_NOT::GetClassData() const { return &_class_data_; }


void C2S_HEARTBEAT_NOT::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<C2S_HEARTBEAT_NOT*>(&to_msg);
  auto& from = static_cast<const C2S_HEARTBEAT_NOT&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.C2S_HEARTBEAT_NOT)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_clienttimestamp() != 0) {
    _this->_internal_set_clienttimestamp(from._internal_clienttimestamp());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void C2S_HEARTBEAT_NOT::CopyFrom(const C2S_HEARTBEAT_NOT& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.C2S_HEARTBEAT_NOT)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool C2S_HEARTBEAT_NOT::IsInitialized() const {
  return true;
}

void C2S_HEARTBEAT_NOT::InternalSwap(C2S_HEARTBEAT_NOT* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.clienttimestamp_, other->_impl_.clienttimestamp_);
}

::PROTOBUF_NAMESPACE_ID::Metadata C2S_HEARTBEAT_NOT::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Heartbeat_2eproto_getter, &descriptor_table_Heartbeat_2eproto_once,
      file_level_metadata_Heartbeat_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Protocol::C2S_HEARTBEAT_NOT*
Arena::CreateMaybeMessage< ::Protocol::C2S_HEARTBEAT_NOT >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::C2S_HEARTBEAT_NOT >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
