// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Login.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Login_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Login_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_bases.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Enum.pb.h"
#include "PacketOption.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Login_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Login_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Login_2eproto;
namespace Protocol {
class C2S_LOGIN_REQ;
struct C2S_LOGIN_REQDefaultTypeInternal;
extern C2S_LOGIN_REQDefaultTypeInternal _C2S_LOGIN_REQ_default_instance_;
class C2S_LOGOUT_NOT;
struct C2S_LOGOUT_NOTDefaultTypeInternal;
extern C2S_LOGOUT_NOTDefaultTypeInternal _C2S_LOGOUT_NOT_default_instance_;
class S2C_KICK_NOT;
struct S2C_KICK_NOTDefaultTypeInternal;
extern S2C_KICK_NOTDefaultTypeInternal _S2C_KICK_NOT_default_instance_;
class S2C_LOGIN_RES;
struct S2C_LOGIN_RESDefaultTypeInternal;
extern S2C_LOGIN_RESDefaultTypeInternal _S2C_LOGIN_RES_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::C2S_LOGIN_REQ* Arena::CreateMaybeMessage<::Protocol::C2S_LOGIN_REQ>(Arena*);
template<> ::Protocol::C2S_LOGOUT_NOT* Arena::CreateMaybeMessage<::Protocol::C2S_LOGOUT_NOT>(Arena*);
template<> ::Protocol::S2C_KICK_NOT* Arena::CreateMaybeMessage<::Protocol::S2C_KICK_NOT>(Arena*);
template<> ::Protocol::S2C_LOGIN_RES* Arena::CreateMaybeMessage<::Protocol::S2C_LOGIN_RES>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class C2S_LOGIN_REQ final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.C2S_LOGIN_REQ) */ {
 public:
  inline C2S_LOGIN_REQ() : C2S_LOGIN_REQ(nullptr) {}
  ~C2S_LOGIN_REQ() override;
  explicit PROTOBUF_CONSTEXPR C2S_LOGIN_REQ(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C2S_LOGIN_REQ(const C2S_LOGIN_REQ& from);
  C2S_LOGIN_REQ(C2S_LOGIN_REQ&& from) noexcept
    : C2S_LOGIN_REQ() {
    *this = ::std::move(from);
  }

  inline C2S_LOGIN_REQ& operator=(const C2S_LOGIN_REQ& from) {
    CopyFrom(from);
    return *this;
  }
  inline C2S_LOGIN_REQ& operator=(C2S_LOGIN_REQ&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C2S_LOGIN_REQ& default_instance() {
    return *internal_default_instance();
  }
  static inline const C2S_LOGIN_REQ* internal_default_instance() {
    return reinterpret_cast<const C2S_LOGIN_REQ*>(
               &_C2S_LOGIN_REQ_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(C2S_LOGIN_REQ& a, C2S_LOGIN_REQ& b) {
    a.Swap(&b);
  }
  inline void Swap(C2S_LOGIN_REQ* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C2S_LOGIN_REQ* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C2S_LOGIN_REQ* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<C2S_LOGIN_REQ>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const C2S_LOGIN_REQ& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const C2S_LOGIN_REQ& from) {
    C2S_LOGIN_REQ::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C2S_LOGIN_REQ* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.C2S_LOGIN_REQ";
  }
  protected:
  explicit C2S_LOGIN_REQ(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTicketFieldNumber = 2,
    kAccountIdFieldNumber = 1,
  };
  // string ticket = 2;
  void clear_ticket();
  const std::string& ticket() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_ticket(ArgT0&& arg0, ArgT... args);
  std::string* mutable_ticket();
  PROTOBUF_NODISCARD std::string* release_ticket();
  void set_allocated_ticket(std::string* ticket);
  private:
  const std::string& _internal_ticket() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ticket(const std::string& value);
  std::string* _internal_mutable_ticket();
  public:

  // uint64 accountId = 1;
  void clear_accountid();
  uint64_t accountid() const;
  void set_accountid(uint64_t value);
  private:
  uint64_t _internal_accountid() const;
  void _internal_set_accountid(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.C2S_LOGIN_REQ)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ticket_;
    uint64_t accountid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Login_2eproto;
};
// -------------------------------------------------------------------

class S2C_LOGIN_RES final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S2C_LOGIN_RES) */ {
 public:
  inline S2C_LOGIN_RES() : S2C_LOGIN_RES(nullptr) {}
  ~S2C_LOGIN_RES() override;
  explicit PROTOBUF_CONSTEXPR S2C_LOGIN_RES(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S2C_LOGIN_RES(const S2C_LOGIN_RES& from);
  S2C_LOGIN_RES(S2C_LOGIN_RES&& from) noexcept
    : S2C_LOGIN_RES() {
    *this = ::std::move(from);
  }

  inline S2C_LOGIN_RES& operator=(const S2C_LOGIN_RES& from) {
    CopyFrom(from);
    return *this;
  }
  inline S2C_LOGIN_RES& operator=(S2C_LOGIN_RES&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S2C_LOGIN_RES& default_instance() {
    return *internal_default_instance();
  }
  static inline const S2C_LOGIN_RES* internal_default_instance() {
    return reinterpret_cast<const S2C_LOGIN_RES*>(
               &_S2C_LOGIN_RES_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(S2C_LOGIN_RES& a, S2C_LOGIN_RES& b) {
    a.Swap(&b);
  }
  inline void Swap(S2C_LOGIN_RES* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S2C_LOGIN_RES* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S2C_LOGIN_RES* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S2C_LOGIN_RES>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S2C_LOGIN_RES& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S2C_LOGIN_RES& from) {
    S2C_LOGIN_RES::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S2C_LOGIN_RES* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S2C_LOGIN_RES";
  }
  protected:
  explicit S2C_LOGIN_RES(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResultFieldNumber = 1,
  };
  // .Protocol.eLoginResult result = 1;
  void clear_result();
  ::Protocol::eLoginResult result() const;
  void set_result(::Protocol::eLoginResult value);
  private:
  ::Protocol::eLoginResult _internal_result() const;
  void _internal_set_result(::Protocol::eLoginResult value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S2C_LOGIN_RES)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int result_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Login_2eproto;
};
// -------------------------------------------------------------------

class C2S_LOGOUT_NOT final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:Protocol.C2S_LOGOUT_NOT) */ {
 public:
  inline C2S_LOGOUT_NOT() : C2S_LOGOUT_NOT(nullptr) {}
  explicit PROTOBUF_CONSTEXPR C2S_LOGOUT_NOT(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C2S_LOGOUT_NOT(const C2S_LOGOUT_NOT& from);
  C2S_LOGOUT_NOT(C2S_LOGOUT_NOT&& from) noexcept
    : C2S_LOGOUT_NOT() {
    *this = ::std::move(from);
  }

  inline C2S_LOGOUT_NOT& operator=(const C2S_LOGOUT_NOT& from) {
    CopyFrom(from);
    return *this;
  }
  inline C2S_LOGOUT_NOT& operator=(C2S_LOGOUT_NOT&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C2S_LOGOUT_NOT& default_instance() {
    return *internal_default_instance();
  }
  static inline const C2S_LOGOUT_NOT* internal_default_instance() {
    return reinterpret_cast<const C2S_LOGOUT_NOT*>(
               &_C2S_LOGOUT_NOT_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(C2S_LOGOUT_NOT& a, C2S_LOGOUT_NOT& b) {
    a.Swap(&b);
  }
  inline void Swap(C2S_LOGOUT_NOT* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C2S_LOGOUT_NOT* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C2S_LOGOUT_NOT* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<C2S_LOGOUT_NOT>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const C2S_LOGOUT_NOT& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const C2S_LOGOUT_NOT& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.C2S_LOGOUT_NOT";
  }
  protected:
  explicit C2S_LOGOUT_NOT(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Protocol.C2S_LOGOUT_NOT)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_Login_2eproto;
};
// -------------------------------------------------------------------

class S2C_KICK_NOT final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S2C_KICK_NOT) */ {
 public:
  inline S2C_KICK_NOT() : S2C_KICK_NOT(nullptr) {}
  ~S2C_KICK_NOT() override;
  explicit PROTOBUF_CONSTEXPR S2C_KICK_NOT(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S2C_KICK_NOT(const S2C_KICK_NOT& from);
  S2C_KICK_NOT(S2C_KICK_NOT&& from) noexcept
    : S2C_KICK_NOT() {
    *this = ::std::move(from);
  }

  inline S2C_KICK_NOT& operator=(const S2C_KICK_NOT& from) {
    CopyFrom(from);
    return *this;
  }
  inline S2C_KICK_NOT& operator=(S2C_KICK_NOT&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S2C_KICK_NOT& default_instance() {
    return *internal_default_instance();
  }
  static inline const S2C_KICK_NOT* internal_default_instance() {
    return reinterpret_cast<const S2C_KICK_NOT*>(
               &_S2C_KICK_NOT_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(S2C_KICK_NOT& a, S2C_KICK_NOT& b) {
    a.Swap(&b);
  }
  inline void Swap(S2C_KICK_NOT* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S2C_KICK_NOT* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S2C_KICK_NOT* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S2C_KICK_NOT>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S2C_KICK_NOT& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S2C_KICK_NOT& from) {
    S2C_KICK_NOT::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S2C_KICK_NOT* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S2C_KICK_NOT";
  }
  protected:
  explicit S2C_KICK_NOT(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kReasonFieldNumber = 1,
  };
  // string reason = 1;
  void clear_reason();
  const std::string& reason() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_reason(ArgT0&& arg0, ArgT... args);
  std::string* mutable_reason();
  PROTOBUF_NODISCARD std::string* release_reason();
  void set_allocated_reason(std::string* reason);
  private:
  const std::string& _internal_reason() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_reason(const std::string& value);
  std::string* _internal_mutable_reason();
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S2C_KICK_NOT)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr reason_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Login_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// C2S_LOGIN_REQ

// uint64 accountId = 1;
inline void C2S_LOGIN_REQ::clear_accountid() {
  _impl_.accountid_ = uint64_t{0u};
}
inline uint64_t C2S_LOGIN_REQ::_internal_accountid() const {
  return _impl_.accountid_;
}
inline uint64_t C2S_LOGIN_REQ::accountid() const {
  // @@protoc_insertion_point(field_get:Protocol.C2S_LOGIN_REQ.accountId)
  return _internal_accountid();
}
inline void C2S_LOGIN_REQ::_internal_set_accountid(uint64_t value) {
  
  _impl_.accountid_ = value;
}
inline void C2S_LOGIN_REQ::set_accountid(uint64_t value) {
  _internal_set_accountid(value);
  // @@protoc_insertion_point(field_set:Protocol.C2S_LOGIN_REQ.accountId)
}

// string ticket = 2;
inline void C2S_LOGIN_REQ::clear_ticket() {
  _impl_.ticket_.ClearToEmpty();
}
inline const std::string& C2S_LOGIN_REQ::ticket() const {
  // @@protoc_insertion_point(field_get:Protocol.C2S_LOGIN_REQ.ticket)
  return _internal_ticket();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void C2S_LOGIN_REQ::set_ticket(ArgT0&& arg0, ArgT... args) {
 
 _impl_.ticket_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.C2S_LOGIN_REQ.ticket)
}
inline std::string* C2S_LOGIN_REQ::mutable_ticket() {
  std::string* _s = _internal_mutable_ticket();
  // @@protoc_insertion_point(field_mutable:Protocol.C2S_LOGIN_REQ.ticket)
  return _s;
}
inline const std::string& C2S_LOGIN_REQ::_internal_ticket() const {
  return _impl_.ticket_.Get();
}
inline void C2S_LOGIN_REQ::_internal_set_ticket(const std::string& value) {
  
  _impl_.ticket_.Set(value, GetArenaForAllocation());
}
inline std::string* C2S_LOGIN_REQ::_internal_mutable_ticket() {
  
  return _impl_.ticket_.Mutable(GetArenaForAllocation());
}
inline std::string* C2S_LOGIN_REQ::release_ticket() {
  // @@protoc_insertion_point(field_release:Protocol.C2S_LOGIN_REQ.ticket)
  return _impl_.ticket_.Release();
}
inline void C2S_LOGIN_REQ::set_allocated_ticket(std::string* ticket) {
  if (ticket != nullptr) {
    
  } else {
    
  }
  _impl_.ticket_.SetAllocated(ticket, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.ticket_.IsDefault()) {
    _impl_.ticket_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.C2S_LOGIN_REQ.ticket)
}

// -------------------------------------------------------------------

// S2C_LOGIN_RES

// .Protocol.eLoginResult result = 1;
inline void S2C_LOGIN_RES::clear_result() {
  _impl_.result_ = 0;
}
inline ::Protocol::eLoginResult S2C_LOGIN_RES::_internal_result() const {
  return static_cast< ::Protocol::eLoginResult >(_impl_.result_);
}
inline ::Protocol::eLoginResult S2C_LOGIN_RES::result() const {
  // @@protoc_insertion_point(field_get:Protocol.S2C_LOGIN_RES.result)
  return _internal_result();
}
inline void S2C_LOGIN_RES::_internal_set_result(::Protocol::eLoginResult value) {
  
  _impl_.result_ = value;
}
inline void S2C_LOGIN_RES::set_result(::Protocol::eLoginResult value) {
  _internal_set_result(value);
  // @@protoc_insertion_point(field_set:Protocol.S2C_LOGIN_RES.result)
}

// -------------------------------------------------------------------

// C2S_LOGOUT_NOT

// -------------------------------------------------------------------

// S2C_KICK_NOT

// string reason = 1;
inline void S2C_KICK_NOT::clear_reason() {
  _impl_.reason_.ClearToEmpty();
}
inline const std::string& S2C_KICK_NOT::reason() const {
  // @@protoc_insertion_point(field_get:Protocol.S2C_KICK_NOT.reason)
  return _internal_reason();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void S2C_KICK_NOT::set_reason(ArgT0&& arg0, ArgT... args) {
 
 _impl_.reason_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Protocol.S2C_KICK_NOT.reason)
}
inline std::string* S2C_KICK_NOT::mutable_reason() {
  std::string* _s = _internal_mutable_reason();
  // @@protoc_insertion_point(field_mutable:Protocol.S2C_KICK_NOT.reason)
  return _s;
}
inline const std::string& S2C_KICK_NOT::_internal_reason() const {
  return _impl_.reason_.Get();
}
inline void S2C_KICK_NOT::_internal_set_reason(const std::string& value) {
  
  _impl_.reason_.Set(value, GetArenaForAllocation());
}
inline std::string* S2C_KICK_NOT::_internal_mutable_reason() {
  
  return _impl_.reason_.Mutable(GetArenaForAllocation());
}
inline std::string* S2C_KICK_NOT::release_reason() {
  // @@protoc_insertion_point(field_release:Protocol.S2C_KICK_NOT.reason)
  return _impl_.reason_.Release();
}
inline void S2C_KICK_NOT::set_allocated_reason(std::string* reason) {
  if (reason != nullptr) {
    
  } else {
    
  }
  _impl_.reason_.SetAllocated(reason, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.reason_.IsDefault()) {
    _impl_.reason_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Protocol.S2C_KICK_NOT.reason)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Login_2eproto
