// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PacketOption.proto
// Protobuf C++ Version: 5.29.5

#include "PacketOption.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Protocol {
}  // namespace Protocol
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_PacketOption_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_PacketOption_2eproto = nullptr;
const ::uint32_t TableStruct_PacketOption_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;
const char descriptor_table_protodef_PacketOption_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\022PacketOption.proto\022\010Protocol\032\nEnum.pro"
    "to\032 google/protobuf/descriptor.proto:L\n\014"
    "service_type\022\034.google.protobuf.FileOptio"
    "ns\030\321\206\003 \001(\0162\026.Protocol.eServiceType:4\n\014ha"
    "ndler_name\022\034.google.protobuf.FileOptions"
    "\030\322\206\003 \001(\t:4\n\tpacket_id\022\037.google.protobuf."
    "MessageOptions\030\323\206\003 \001(\005:B\n\006sender\022\037.googl"
    "e.protobuf.MessageOptions\030\324\206\003 \001(\0162\017.Prot"
    "ocol.eRole:D\n\010receiver\022\037.google.protobuf"
    ".MessageOptions\030\325\206\003 \003(\0162\017.Protocol.eRole"
    "b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_PacketOption_2eproto_deps[2] =
    {
        &::descriptor_table_Enum_2eproto,
        &::descriptor_table_google_2fprotobuf_2fdescriptor_2eproto,
};
static ::absl::once_flag descriptor_table_PacketOption_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_PacketOption_2eproto = {
    false,
    false,
    408,
    descriptor_table_protodef_PacketOption_2eproto,
    "PacketOption.proto",
    &descriptor_table_PacketOption_2eproto_once,
    descriptor_table_PacketOption_2eproto_deps,
    2,
    0,
    schemas,
    file_default_instances,
    TableStruct_PacketOption_2eproto::offsets,
    file_level_enum_descriptors_PacketOption_2eproto,
    file_level_service_descriptors_PacketOption_2eproto,
};
namespace Protocol {
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::
        ExtensionIdentifier<::google::protobuf::FileOptions, ::_pbi::EnumTypeTraits< ::Protocol::eServiceType, ::Protocol::eServiceType_IsValid>,
                            14, false>
            service_type(kServiceTypeFieldNumber, static_cast< ::Protocol::eServiceType >(0));
const std::string handler_name_default("");
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::
        ExtensionIdentifier<::google::protobuf::FileOptions, ::_pbi::StringTypeTraits,
                            9, false>
            handler_name(kHandlerNameFieldNumber, handler_name_default);
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::
        ExtensionIdentifier<::google::protobuf::MessageOptions, ::_pbi::PrimitiveTypeTraits< ::int32_t >,
                            5, false>
            packet_id(kPacketIdFieldNumber, 0);
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::
        ExtensionIdentifier<::google::protobuf::MessageOptions, ::_pbi::EnumTypeTraits< ::Protocol::eRole, ::Protocol::eRole_IsValid>,
                            14, false>
            sender(kSenderFieldNumber, static_cast< ::Protocol::eRole >(0));
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::
        ExtensionIdentifier<::google::protobuf::MessageOptions, ::_pbi::RepeatedEnumTypeTraits< ::Protocol::eRole, ::Protocol::eRole_IsValid>,
                            14, true>
            receiver(kReceiverFieldNumber, static_cast< ::Protocol::eRole >(0));
// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_PacketOption_2eproto),
        ::_pbi::ExtensionSet::RegisterEnumExtension(
            &::google::protobuf::FileOptions::default_instance(), 50001, 14,
            false, false, ::Protocol::eServiceType_IsValid),
        ::_pbi::ExtensionSet::RegisterExtension(
            &::google::protobuf::FileOptions::default_instance(), 50002, 9,
            false, false),
        ::_pbi::ExtensionSet::RegisterExtension(
            &::google::protobuf::MessageOptions::default_instance(), 50003, 5,
            false, false),
        ::_pbi::ExtensionSet::RegisterEnumExtension(
            &::google::protobuf::MessageOptions::default_instance(), 50004, 14,
            false, false, ::Protocol::eRole_IsValid),
        ::_pbi::ExtensionSet::RegisterEnumExtension(
            &::google::protobuf::MessageOptions::default_instance(), 50005, 14,
            true, true, ::Protocol::eRole_IsValid),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
