namespace PacketGenerator
{
    internal static class PacketFormatter
    {
        public static readonly string AUTO_GENERATED_WARNING =
            @"// =============================================================================
// AUTO-GENERATED FILE - DO NOT EDIT
// This file is generated by PacketGenerator. Any manual changes will be lost.
// =============================================================================
";

        public static readonly string ENUM_PACKET_ID_FORMAT =
            @"// =============================================================================
// AUTO-GENERATED FILE - DO NOT EDIT
// This file is generated by PacketGenerator. Any manual changes will be lost.
// =============================================================================
#pragma once

#include ""Types.h""

namespace packet_id
{{{0}}}";

        public static readonly string HANDLE_SERVICE_TYPE_FILE_FORMAT =
            @"// =============================================================================
// AUTO-GENERATED FILE - DO NOT EDIT
// This file is generated by PacketGenerator. Any manual changes will be lost.
// =============================================================================
#pragma once
{0}

class PacketServiceTypeHandler
{{
public:

	using PacketServiceTypeHandle = std::function<bool(const uint16, const uint16, const byte*, const PacketSessionRef&)>;

	static constexpr uint16 GET_SERVICE_TYPE(const uint32 packetId) {{ return (packetId >> 16) & 0x0000FFFF; }}
	static constexpr uint16 GET_PACKET_ID(const uint32 packetId) {{ return packetId & 0x0000FFFF; }}

	static void Init()
	{{
        {1}
		{2}
	}}

	static bool HandlePacketServiceType(const uint16 len, const byte* pBuffer, const PacketSessionRef& pSession)
	{{
		const auto [packetSize, headerId] = *(reinterpret_cast<const PacketHeader*>(pBuffer));
		
		const uint16 serviceType = GET_SERVICE_TYPE(headerId);
		const uint16 packetId = GET_PACKET_ID(headerId);

		const auto iter = sPacketServiceTypeMap.find(serviceType);
		if (iter != sPacketServiceTypeMap.end())
		{{
			return iter->second(packetSize, packetId, pBuffer, pSession);
		}}

		return HANDLE_SERVICE_TYPE_INVALID(packetSize, packetId, pBuffer, pSession);
	}}

	static bool HANDLE_SERVICE_TYPE_INVALID(const uint16 size, const uint16 packetId, const byte* pBuffer, const PacketSessionRef& pSession);

private:

	inline static HashMap<uint16, PacketServiceTypeHandle> sPacketServiceTypeMap;
}};";

        public static readonly string SERVICE_TYPE_INCLUDE_FORMAT =
            @"#include ""{0}.h""
";

        public static readonly string SERVICE_TYPE_INIT_FORMAT =
            @"{0}::Init();
";

        public static readonly string SERVICE_TYPE_HANDLE_INIT_FORMAT =
            @"sPacketServiceTypeMap[Protocol::eServiceType::{0}] = [](const uint16 size, const uint16 packetId, const byte* pBuffer, const PacketSessionRef& pSession) -> bool
            {{
                return {1}::HandlePacket(size, packetId, pBuffer, pSession);
            }};

";

        public static readonly string HANDLE_FILE_FORMAT =
            @"// =============================================================================
// AUTO-GENERATED FILE - DO NOT EDIT
// This file is generated by PacketGenerator. Any manual changes will be lost.
// =============================================================================
// ReSharper disable CppInconsistentNaming
#pragma once

#ifdef _UNREAL_

#include ""Network/CppNetEngine/NetEngineWrapper.h""
#include ""Network/ProtocolHeader/ProtocolWrapper.h""

#else

#include ""Enum.pb.h""
#include ""Struct.pb.h""
#include ""PacketOption.pb.h""
#include ""PacketId.h""
#include ""{0}.pb.h""
#include ""CrashReporter.h""
#include ""NetEngineMacro.h""
#include ""PacketSession.h""

#endif

class {1}
{{
public:

    using PacketHandle = std::function<bool(const uint16, const byte*, const PacketSessionRef&)>;

    static constexpr uint32 MAKE_PACKET_HEADER_ID(const uint16 serviceType, const uint16 packetId)
    {{
        return (static_cast<uint32>(serviceType) << 16) | static_cast<uint32>(packetId);
    }}

    static void Init()
    {{
        {2}
    }}

	static bool HandlePacket(const uint16 size, const uint16 packetId, const byte* pBuffer, const PacketSessionRef& pSession)
	{{
		const auto iter = sPacketHandleMap.find(packetId);
		if (iter != sPacketHandleMap.end())
		{{
			return iter->second(size, pBuffer, pSession);
		}}

		return HANDLE_PACKET_ID_INVALID(size, packetId, pBuffer, pSession);
	}}

	static bool HANDLE_PACKET_ID_INVALID(const uint16 size, const uint16 packetId, const byte* pBuffer, const PacketSessionRef& pSession);
    {3}
    
    {4}

private:

	template<typename PacketType, typename Handle>
	static bool HandlePacket(const uint16 size, const byte* pBuffer, const PacketSessionRef& pSession, Handle handlePacket)
	{{
		PacketType packet{{}};
		if (packet.ParseFromArray(pBuffer + SIZE_OF_16(PacketHeader), size - SIZE_OF_16(PacketHeader)) == false)
		{{
			return false;
		}}

		return handlePacket(packet, pSession);
	}}

    template<typename T>
	static NetSendBufferRef MakeSendBuffer(const T& packet, const uint16 packetId)
	{{
		const uint16 dataSize = static_cast<uint16>(packet.ByteSizeLong());
		const uint16 packetSize = dataSize + sizeof(PacketHeader);

	    if (packetSize > std::numeric_limits<uint16>::max())
	    {{
		    NET_ENGINE_LOG_FATAL(""MakeSendBuffer Size Overflow, packetId : {{}}, packetSize : {{}}"", packetId, packetSize);
		    CrashReporter::Crash();
	    }}

		auto sendBuffer = cpp_net_engine::MakeSendBuffer(packetSize);

		byte* pBuffer = sendBuffer->Reserve(packetSize);
		if (pBuffer == nullptr)
		{{
			NET_ENGINE_LOG_FATAL(""MakeSendBuffer sendBuffer->Reserve(packetSize) is failed"");
			CrashReporter::Crash();
		}}

		auto* header = reinterpret_cast<PacketHeader*>(pBuffer);
		header->size = packetSize;
		header->id = MAKE_PACKET_HEADER_ID(Protocol::eServiceType::{5}, packetId);
		if (!packet.SerializeToArray(&header[1], dataSize))
		{{
			NET_ENGINE_LOG_FATAL(""{0}::MakeSendBuffer SerializeToArray is Failed, &header[1] : {{}}, packetId : {{}}, dataSize : {{}}"", fmt::ptr(&header[1]), header->id, dataSize);
			CrashReporter::Crash();
	    }}
		
        sendBuffer->Commit(packetSize);
		
        return sendBuffer;
	}}

	inline static HashMap<uint16, PacketHandle> sPacketHandleMap;
}};";

        public static readonly string PROTO_FILE_INCLUDE_FORMAT = "";

        public static readonly string RECEIVE_HANDLE_INIT_FORMAT =
            @"sPacketHandleMap[packet_id::e{0}PacketId::{1}] = [](const uint16 size, const byte* pBuffer, const PacketSessionRef& pSession)->bool
			{{
				return HandlePacket<Protocol::{1}>(size, pBuffer, pSession, HANDLE_{1});
			}};
";

		public static readonly string RECEIVE_HANDLE_DECLARE_FORMAT =
            @"static bool HANDLE_{0}(const Protocol::{0}& packet, const PacketSessionRef& pSession);
";

        public static readonly string SEND_MAKE_SEND_BUFFER_FORMAT =
            @"static NetSendBufferRef MakeSendBuffer(const Protocol::{0}& packet) {{ return MakeSendBuffer(packet, packet_id::{1}); }}
";
    }
}
