// =============================================================================
// AUTO-GENERATED FILE - DO NOT EDIT
// This file is generated by PacketGenerator. Any manual changes will be lost.
// =============================================================================
#pragma once

namespace packet_id
{
	enum eEchoPacketId : uint16
	{
        C2S_ECHO_REQ = 1,
        S2C_ECHO_RES = 2,
	};


	enum eHeartbeatPacketId : uint16
	{
        C2S_HEARTBEAT_REQ = 1,
        S2C_HEARTBEAT_RES = 2,
	};


	enum eLoginPacketId : uint16
	{
        C2S_LOGIN_REQ = 1,
        S2C_LOGIN_RES = 2,
	};


	enum eServerHeartbeatPacketId : uint16
	{
        S2S_HEARTBEAT_REQ = 1,
        S2S_HEARTBEAT_RES = 2,
	};

}