// =============================================================================
// AUTO-GENERATED FILE - DO NOT EDIT
// This file is generated by PacketGenerator. Any manual changes will be lost.
// =============================================================================
#pragma once

namespace packet_id
{
	enum eEchoPacketId : uint16
	{
        C2S_ECHO_REQ = 1,
        S2C_ECHO_RES = 2,
	};


	enum eHeartbeatPacketId : uint16
	{
        C2S_HEARTBEAT_NOT = 1,
	};


	enum eLoginPacketId : uint16
	{
        C2S_LOGIN_REQ = 1,
        S2C_LOGIN_RES = 2,
	};


	enum eServerHeartbeatPacketId : uint16
	{
        S2S_HEARTBEAT_NOT = 1,
	};


	enum eWorldPacketId : uint16
	{
        C2S_WORLD_LIST_REQ = 1,
        S2C_WORLD_LIST_RES = 2,
        C2S_WORLD_SELECT_REQ = 3,
        S2C_WORLD_SELECT_RES = 4,
	};

}