syntax = "proto3";
package Protocol;

enum eServiceType 
{
    SERVICE_TYPE_NONE = 0;
    SERVICE_TYPE_ECHO = 1;
    SERVICE_TYPE_LOGIN = 2;
    SERVICE_TYPE_HEARTBEAT = 3;
    SERVICE_TYPE_SERVER_HEARTBEAT = 4;
}

enum eRole
{
    ROLE_NONE = 0;
    CLIENT = 1;
    ECHO_CLIENT = 2;
    ECHO_SERVER = 3;
    GATEWAY_SERVER = 4;
    WORLD_SERVER = 5;
    CENTER_SERVER = 6;
    SERVER = 7;
}

enum eLoginResult
{
    LOGIN_SUCCESS = 0;              // 성공
    LOGIN_FAIL_INVALID_TICKET = 1;  // 티켓이 만료되었거나 일치하지 않음 (보안)
    LOGIN_FAIL_SERVER_FULL = 2;     // 게이트웨이 수용 인원 초과 (아까 만든 상태값 연동)
    LOGIN_FAIL_MAINTENANCE = 3;     // 서버 점검 중
    LOGIN_FAIL_INTERNAL_ERROR = 4;  // Redis 조회 실패 등 서버 내부 에러
}