syntax = "proto3";
package Protocol;

import "Enum.proto";
import "Struct.proto";
import "PacketOption.proto";

option (service_type) = SERVICE_TYPE_REALM;
option (handler_name) = "RealmPacketHandler";

message C2S_REALM_LIST_REQ
{
    option (sender) = CLIENT;
    option (receiver) = GATEWAY_SERVER;
}

message S2C_REALM_LIST_RES
{
    option (sender) = GATEWAY_SERVER;
    option (receiver) = CLIENT;

    repeated RealmServerInfo realms = 1;
}

message C2S_REALM_SELECT_REQ
{
    option (sender) = CLIENT;
    option (receiver) = GATEWAY_SERVER;

    int32 realmId = 1;
}

message S2C_REALM_SELECT_RES
{
    option (sender) = GATEWAY_SERVER;
    option (receiver) = CLIENT;

    eRealmSelectResult result = 1;
}
