syntax = "proto3";
package Protocol;

import "PacketOption.proto";

option (service_type) = SERVICE_TYPE_SERVER_HEARTBEAT;
option (handler_name) = "ServerHeartbeatPacketHandler";

message S2S_HEARTBEAT_REQ
{
    option (sender) = WORLD_SERVER;
    option (receiver) = GATEWAY_SERVER;

    int32 serverId = 1;
    int64 timestamp = 2;
    int32 sessionCount = 3;
    int32 status = 4;
}

message S2S_HEARTBEAT_RES
{
    option (sender) = GATEWAY_SERVER;
    option (receiver) = WORLD_SERVER;

    int64 timestamp = 1;
    bool accepted = 2;
}
