syntax = "proto3";
package Protocol;

import "Enum.proto";
import "Struct.proto";
import "PacketOption.proto";

option (service_type) = SERVICE_TYPE_WORLD;
option (handler_name) = "WorldPacketHandler";

message C2S_WORLD_LIST_REQ
{
    option (sender) = CLIENT;
    option (receiver) = GATEWAY_SERVER;
}

message S2C_WORLD_LIST_RES
{
    option (sender) = GATEWAY_SERVER;
    option (receiver) = CLIENT;

    repeated WorldServerInfo worlds = 1;
}

message C2S_WORLD_SELECT_REQ
{
    option (sender) = CLIENT;
    option (receiver) = GATEWAY_SERVER;

    int32 worldId = 1;
}

message S2C_WORLD_SELECT_RES
{
    option (sender) = GATEWAY_SERVER;
    option (receiver) = CLIENT;

    eWorldSelectResult result = 1;
}
