// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enum.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Enum_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Enum_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Enum_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

enum eServiceType : int {
  SERVICE_TYPE_NONE = 0,
  SERVICE_TYPE_ECHO = 1,
  SERVICE_TYPE_LOGIN = 2,
  SERVICE_TYPE_HEARTBEAT = 3,
  SERVICE_TYPE_SERVER_HEARTBEAT = 4,
  SERVICE_TYPE_REALM = 5,
  SERVICE_TYPE_GAME_SESSION = 6,
  SERVICE_TYPE_MOVEMENT = 7,
  eServiceType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  eServiceType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool eServiceType_IsValid(int value);
constexpr eServiceType eServiceType_MIN = SERVICE_TYPE_NONE;
constexpr eServiceType eServiceType_MAX = SERVICE_TYPE_MOVEMENT;
constexpr int eServiceType_ARRAYSIZE = eServiceType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* eServiceType_descriptor();
template<typename T>
inline const std::string& eServiceType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, eServiceType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function eServiceType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    eServiceType_descriptor(), enum_t_value);
}
inline bool eServiceType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, eServiceType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<eServiceType>(
    eServiceType_descriptor(), name, value);
}
enum eRole : int {
  ROLE_NONE = 0,
  CLIENT = 1,
  ECHO_CLIENT = 2,
  ECHO_SERVER = 3,
  GATEWAY_SERVER = 4,
  WORLD_SERVER = 5,
  CENTER_SERVER = 6,
  SERVER = 7,
  REALM_SERVER = 8,
  eRole_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  eRole_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool eRole_IsValid(int value);
constexpr eRole eRole_MIN = ROLE_NONE;
constexpr eRole eRole_MAX = REALM_SERVER;
constexpr int eRole_ARRAYSIZE = eRole_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* eRole_descriptor();
template<typename T>
inline const std::string& eRole_Name(T enum_t_value) {
  static_assert(::std::is_same<T, eRole>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function eRole_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    eRole_descriptor(), enum_t_value);
}
inline bool eRole_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, eRole* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<eRole>(
    eRole_descriptor(), name, value);
}
enum eLoginResult : int {
  LOGIN_SUCCESS = 0,
  LOGIN_FAIL_INVALID_TICKET = 1,
  LOGIN_FAIL_SERVER_FULL = 2,
  LOGIN_FAIL_MAINTENANCE = 3,
  LOGIN_FAIL_INTERNAL_ERROR = 4,
  eLoginResult_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  eLoginResult_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool eLoginResult_IsValid(int value);
constexpr eLoginResult eLoginResult_MIN = LOGIN_SUCCESS;
constexpr eLoginResult eLoginResult_MAX = LOGIN_FAIL_INTERNAL_ERROR;
constexpr int eLoginResult_ARRAYSIZE = eLoginResult_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* eLoginResult_descriptor();
template<typename T>
inline const std::string& eLoginResult_Name(T enum_t_value) {
  static_assert(::std::is_same<T, eLoginResult>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function eLoginResult_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    eLoginResult_descriptor(), enum_t_value);
}
inline bool eLoginResult_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, eLoginResult* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<eLoginResult>(
    eLoginResult_descriptor(), name, value);
}
enum eRealmSelectResult : int {
  REALM_SELECT_SUCCESS = 0,
  REALM_SELECT_FAIL_NOT_FOUND = 1,
  REALM_SELECT_FAIL_FULL = 2,
  REALM_SELECT_FAIL_MAINTENANCE = 3,
  eRealmSelectResult_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  eRealmSelectResult_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool eRealmSelectResult_IsValid(int value);
constexpr eRealmSelectResult eRealmSelectResult_MIN = REALM_SELECT_SUCCESS;
constexpr eRealmSelectResult eRealmSelectResult_MAX = REALM_SELECT_FAIL_MAINTENANCE;
constexpr int eRealmSelectResult_ARRAYSIZE = eRealmSelectResult_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* eRealmSelectResult_descriptor();
template<typename T>
inline const std::string& eRealmSelectResult_Name(T enum_t_value) {
  static_assert(::std::is_same<T, eRealmSelectResult>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function eRealmSelectResult_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    eRealmSelectResult_descriptor(), enum_t_value);
}
inline bool eRealmSelectResult_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, eRealmSelectResult* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<eRealmSelectResult>(
    eRealmSelectResult_descriptor(), name, value);
}
enum eGameSessionResult : int {
  GAME_SESSION_SUCCESS = 0,
  GAME_SESSION_FAIL_FULL = 1,
  GAME_SESSION_FAIL_DUPLICATE = 2,
  GAME_SESSION_FAIL_INTERNAL = 3,
  eGameSessionResult_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  eGameSessionResult_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool eGameSessionResult_IsValid(int value);
constexpr eGameSessionResult eGameSessionResult_MIN = GAME_SESSION_SUCCESS;
constexpr eGameSessionResult eGameSessionResult_MAX = GAME_SESSION_FAIL_INTERNAL;
constexpr int eGameSessionResult_ARRAYSIZE = eGameSessionResult_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* eGameSessionResult_descriptor();
template<typename T>
inline const std::string& eGameSessionResult_Name(T enum_t_value) {
  static_assert(::std::is_same<T, eGameSessionResult>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function eGameSessionResult_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    eGameSessionResult_descriptor(), enum_t_value);
}
inline bool eGameSessionResult_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, eGameSessionResult* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<eGameSessionResult>(
    eGameSessionResult_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::Protocol::eServiceType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::eServiceType>() {
  return ::Protocol::eServiceType_descriptor();
}
template <> struct is_proto_enum< ::Protocol::eRole> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::eRole>() {
  return ::Protocol::eRole_descriptor();
}
template <> struct is_proto_enum< ::Protocol::eLoginResult> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::eLoginResult>() {
  return ::Protocol::eLoginResult_descriptor();
}
template <> struct is_proto_enum< ::Protocol::eRealmSelectResult> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::eRealmSelectResult>() {
  return ::Protocol::eRealmSelectResult_descriptor();
}
template <> struct is_proto_enum< ::Protocol::eGameSessionResult> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Protocol::eGameSessionResult>() {
  return ::Protocol::eGameSessionResult_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Enum_2eproto
