// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Movement.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Movement_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Movement_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_bases.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Enum.pb.h"
#include "Struct.pb.h"
#include "PacketOption.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Movement_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Movement_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Movement_2eproto;
namespace Protocol {
class C2S_MOVE_INPUT_NOT;
struct C2S_MOVE_INPUT_NOTDefaultTypeInternal;
extern C2S_MOVE_INPUT_NOTDefaultTypeInternal _C2S_MOVE_INPUT_NOT_default_instance_;
class C2S_SPAWN_POSITION_REQ;
struct C2S_SPAWN_POSITION_REQDefaultTypeInternal;
extern C2S_SPAWN_POSITION_REQDefaultTypeInternal _C2S_SPAWN_POSITION_REQ_default_instance_;
class S2C_ENTITY_ENTER_NOT;
struct S2C_ENTITY_ENTER_NOTDefaultTypeInternal;
extern S2C_ENTITY_ENTER_NOTDefaultTypeInternal _S2C_ENTITY_ENTER_NOT_default_instance_;
class S2C_ENTITY_LEAVE_NOT;
struct S2C_ENTITY_LEAVE_NOTDefaultTypeInternal;
extern S2C_ENTITY_LEAVE_NOTDefaultTypeInternal _S2C_ENTITY_LEAVE_NOT_default_instance_;
class S2C_ENTITY_SNAPSHOT_NOT;
struct S2C_ENTITY_SNAPSHOT_NOTDefaultTypeInternal;
extern S2C_ENTITY_SNAPSHOT_NOTDefaultTypeInternal _S2C_ENTITY_SNAPSHOT_NOT_default_instance_;
class S2C_MOVE_RESULT_NOT;
struct S2C_MOVE_RESULT_NOTDefaultTypeInternal;
extern S2C_MOVE_RESULT_NOTDefaultTypeInternal _S2C_MOVE_RESULT_NOT_default_instance_;
class S2C_SPAWN_POSITION_RES;
struct S2C_SPAWN_POSITION_RESDefaultTypeInternal;
extern S2C_SPAWN_POSITION_RESDefaultTypeInternal _S2C_SPAWN_POSITION_RES_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::C2S_MOVE_INPUT_NOT* Arena::CreateMaybeMessage<::Protocol::C2S_MOVE_INPUT_NOT>(Arena*);
template<> ::Protocol::C2S_SPAWN_POSITION_REQ* Arena::CreateMaybeMessage<::Protocol::C2S_SPAWN_POSITION_REQ>(Arena*);
template<> ::Protocol::S2C_ENTITY_ENTER_NOT* Arena::CreateMaybeMessage<::Protocol::S2C_ENTITY_ENTER_NOT>(Arena*);
template<> ::Protocol::S2C_ENTITY_LEAVE_NOT* Arena::CreateMaybeMessage<::Protocol::S2C_ENTITY_LEAVE_NOT>(Arena*);
template<> ::Protocol::S2C_ENTITY_SNAPSHOT_NOT* Arena::CreateMaybeMessage<::Protocol::S2C_ENTITY_SNAPSHOT_NOT>(Arena*);
template<> ::Protocol::S2C_MOVE_RESULT_NOT* Arena::CreateMaybeMessage<::Protocol::S2C_MOVE_RESULT_NOT>(Arena*);
template<> ::Protocol::S2C_SPAWN_POSITION_RES* Arena::CreateMaybeMessage<::Protocol::S2C_SPAWN_POSITION_RES>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class C2S_MOVE_INPUT_NOT final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.C2S_MOVE_INPUT_NOT) */ {
 public:
  inline C2S_MOVE_INPUT_NOT() : C2S_MOVE_INPUT_NOT(nullptr) {}
  ~C2S_MOVE_INPUT_NOT() override;
  explicit PROTOBUF_CONSTEXPR C2S_MOVE_INPUT_NOT(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C2S_MOVE_INPUT_NOT(const C2S_MOVE_INPUT_NOT& from);
  C2S_MOVE_INPUT_NOT(C2S_MOVE_INPUT_NOT&& from) noexcept
    : C2S_MOVE_INPUT_NOT() {
    *this = ::std::move(from);
  }

  inline C2S_MOVE_INPUT_NOT& operator=(const C2S_MOVE_INPUT_NOT& from) {
    CopyFrom(from);
    return *this;
  }
  inline C2S_MOVE_INPUT_NOT& operator=(C2S_MOVE_INPUT_NOT&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C2S_MOVE_INPUT_NOT& default_instance() {
    return *internal_default_instance();
  }
  static inline const C2S_MOVE_INPUT_NOT* internal_default_instance() {
    return reinterpret_cast<const C2S_MOVE_INPUT_NOT*>(
               &_C2S_MOVE_INPUT_NOT_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(C2S_MOVE_INPUT_NOT& a, C2S_MOVE_INPUT_NOT& b) {
    a.Swap(&b);
  }
  inline void Swap(C2S_MOVE_INPUT_NOT* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C2S_MOVE_INPUT_NOT* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C2S_MOVE_INPUT_NOT* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<C2S_MOVE_INPUT_NOT>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const C2S_MOVE_INPUT_NOT& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const C2S_MOVE_INPUT_NOT& from) {
    C2S_MOVE_INPUT_NOT::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C2S_MOVE_INPUT_NOT* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.C2S_MOVE_INPUT_NOT";
  }
  protected:
  explicit C2S_MOVE_INPUT_NOT(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDirectionFieldNumber = 2,
    kSequenceIdFieldNumber = 1,
    kRotationYawFieldNumber = 3,
    kClientTimestampFieldNumber = 4,
    kPositionZFieldNumber = 5,
  };
  // .Protocol.Vector3 direction = 2;
  bool has_direction() const;
  private:
  bool _internal_has_direction() const;
  public:
  void clear_direction();
  const ::Protocol::Vector3& direction() const;
  PROTOBUF_NODISCARD ::Protocol::Vector3* release_direction();
  ::Protocol::Vector3* mutable_direction();
  void set_allocated_direction(::Protocol::Vector3* direction);
  private:
  const ::Protocol::Vector3& _internal_direction() const;
  ::Protocol::Vector3* _internal_mutable_direction();
  public:
  void unsafe_arena_set_allocated_direction(
      ::Protocol::Vector3* direction);
  ::Protocol::Vector3* unsafe_arena_release_direction();

  // uint32 sequenceId = 1;
  void clear_sequenceid();
  uint32_t sequenceid() const;
  void set_sequenceid(uint32_t value);
  private:
  uint32_t _internal_sequenceid() const;
  void _internal_set_sequenceid(uint32_t value);
  public:

  // float rotationYaw = 3;
  void clear_rotationyaw();
  float rotationyaw() const;
  void set_rotationyaw(float value);
  private:
  float _internal_rotationyaw() const;
  void _internal_set_rotationyaw(float value);
  public:

  // int64 clientTimestamp = 4;
  void clear_clienttimestamp();
  int64_t clienttimestamp() const;
  void set_clienttimestamp(int64_t value);
  private:
  int64_t _internal_clienttimestamp() const;
  void _internal_set_clienttimestamp(int64_t value);
  public:

  // float positionZ = 5;
  void clear_positionz();
  float positionz() const;
  void set_positionz(float value);
  private:
  float _internal_positionz() const;
  void _internal_set_positionz(float value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.C2S_MOVE_INPUT_NOT)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::Protocol::Vector3* direction_;
    uint32_t sequenceid_;
    float rotationyaw_;
    int64_t clienttimestamp_;
    float positionz_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Movement_2eproto;
};
// -------------------------------------------------------------------

class S2C_MOVE_RESULT_NOT final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S2C_MOVE_RESULT_NOT) */ {
 public:
  inline S2C_MOVE_RESULT_NOT() : S2C_MOVE_RESULT_NOT(nullptr) {}
  ~S2C_MOVE_RESULT_NOT() override;
  explicit PROTOBUF_CONSTEXPR S2C_MOVE_RESULT_NOT(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S2C_MOVE_RESULT_NOT(const S2C_MOVE_RESULT_NOT& from);
  S2C_MOVE_RESULT_NOT(S2C_MOVE_RESULT_NOT&& from) noexcept
    : S2C_MOVE_RESULT_NOT() {
    *this = ::std::move(from);
  }

  inline S2C_MOVE_RESULT_NOT& operator=(const S2C_MOVE_RESULT_NOT& from) {
    CopyFrom(from);
    return *this;
  }
  inline S2C_MOVE_RESULT_NOT& operator=(S2C_MOVE_RESULT_NOT&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S2C_MOVE_RESULT_NOT& default_instance() {
    return *internal_default_instance();
  }
  static inline const S2C_MOVE_RESULT_NOT* internal_default_instance() {
    return reinterpret_cast<const S2C_MOVE_RESULT_NOT*>(
               &_S2C_MOVE_RESULT_NOT_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(S2C_MOVE_RESULT_NOT& a, S2C_MOVE_RESULT_NOT& b) {
    a.Swap(&b);
  }
  inline void Swap(S2C_MOVE_RESULT_NOT* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S2C_MOVE_RESULT_NOT* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S2C_MOVE_RESULT_NOT* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S2C_MOVE_RESULT_NOT>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S2C_MOVE_RESULT_NOT& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S2C_MOVE_RESULT_NOT& from) {
    S2C_MOVE_RESULT_NOT::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S2C_MOVE_RESULT_NOT* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S2C_MOVE_RESULT_NOT";
  }
  protected:
  explicit S2C_MOVE_RESULT_NOT(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPositionFieldNumber = 2,
    kVelocityFieldNumber = 3,
    kSequenceIdFieldNumber = 1,
    kRotationYawFieldNumber = 4,
    kServerTimestampFieldNumber = 5,
  };
  // .Protocol.Vector3 position = 2;
  bool has_position() const;
  private:
  bool _internal_has_position() const;
  public:
  void clear_position();
  const ::Protocol::Vector3& position() const;
  PROTOBUF_NODISCARD ::Protocol::Vector3* release_position();
  ::Protocol::Vector3* mutable_position();
  void set_allocated_position(::Protocol::Vector3* position);
  private:
  const ::Protocol::Vector3& _internal_position() const;
  ::Protocol::Vector3* _internal_mutable_position();
  public:
  void unsafe_arena_set_allocated_position(
      ::Protocol::Vector3* position);
  ::Protocol::Vector3* unsafe_arena_release_position();

  // .Protocol.Vector3 velocity = 3;
  bool has_velocity() const;
  private:
  bool _internal_has_velocity() const;
  public:
  void clear_velocity();
  const ::Protocol::Vector3& velocity() const;
  PROTOBUF_NODISCARD ::Protocol::Vector3* release_velocity();
  ::Protocol::Vector3* mutable_velocity();
  void set_allocated_velocity(::Protocol::Vector3* velocity);
  private:
  const ::Protocol::Vector3& _internal_velocity() const;
  ::Protocol::Vector3* _internal_mutable_velocity();
  public:
  void unsafe_arena_set_allocated_velocity(
      ::Protocol::Vector3* velocity);
  ::Protocol::Vector3* unsafe_arena_release_velocity();

  // uint32 sequenceId = 1;
  void clear_sequenceid();
  uint32_t sequenceid() const;
  void set_sequenceid(uint32_t value);
  private:
  uint32_t _internal_sequenceid() const;
  void _internal_set_sequenceid(uint32_t value);
  public:

  // float rotationYaw = 4;
  void clear_rotationyaw();
  float rotationyaw() const;
  void set_rotationyaw(float value);
  private:
  float _internal_rotationyaw() const;
  void _internal_set_rotationyaw(float value);
  public:

  // int64 serverTimestamp = 5;
  void clear_servertimestamp();
  int64_t servertimestamp() const;
  void set_servertimestamp(int64_t value);
  private:
  int64_t _internal_servertimestamp() const;
  void _internal_set_servertimestamp(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S2C_MOVE_RESULT_NOT)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::Protocol::Vector3* position_;
    ::Protocol::Vector3* velocity_;
    uint32_t sequenceid_;
    float rotationyaw_;
    int64_t servertimestamp_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Movement_2eproto;
};
// -------------------------------------------------------------------

class S2C_ENTITY_SNAPSHOT_NOT final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S2C_ENTITY_SNAPSHOT_NOT) */ {
 public:
  inline S2C_ENTITY_SNAPSHOT_NOT() : S2C_ENTITY_SNAPSHOT_NOT(nullptr) {}
  ~S2C_ENTITY_SNAPSHOT_NOT() override;
  explicit PROTOBUF_CONSTEXPR S2C_ENTITY_SNAPSHOT_NOT(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S2C_ENTITY_SNAPSHOT_NOT(const S2C_ENTITY_SNAPSHOT_NOT& from);
  S2C_ENTITY_SNAPSHOT_NOT(S2C_ENTITY_SNAPSHOT_NOT&& from) noexcept
    : S2C_ENTITY_SNAPSHOT_NOT() {
    *this = ::std::move(from);
  }

  inline S2C_ENTITY_SNAPSHOT_NOT& operator=(const S2C_ENTITY_SNAPSHOT_NOT& from) {
    CopyFrom(from);
    return *this;
  }
  inline S2C_ENTITY_SNAPSHOT_NOT& operator=(S2C_ENTITY_SNAPSHOT_NOT&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S2C_ENTITY_SNAPSHOT_NOT& default_instance() {
    return *internal_default_instance();
  }
  static inline const S2C_ENTITY_SNAPSHOT_NOT* internal_default_instance() {
    return reinterpret_cast<const S2C_ENTITY_SNAPSHOT_NOT*>(
               &_S2C_ENTITY_SNAPSHOT_NOT_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(S2C_ENTITY_SNAPSHOT_NOT& a, S2C_ENTITY_SNAPSHOT_NOT& b) {
    a.Swap(&b);
  }
  inline void Swap(S2C_ENTITY_SNAPSHOT_NOT* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S2C_ENTITY_SNAPSHOT_NOT* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S2C_ENTITY_SNAPSHOT_NOT* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S2C_ENTITY_SNAPSHOT_NOT>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S2C_ENTITY_SNAPSHOT_NOT& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S2C_ENTITY_SNAPSHOT_NOT& from) {
    S2C_ENTITY_SNAPSHOT_NOT::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S2C_ENTITY_SNAPSHOT_NOT* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S2C_ENTITY_SNAPSHOT_NOT";
  }
  protected:
  explicit S2C_ENTITY_SNAPSHOT_NOT(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEntitiesFieldNumber = 1,
    kServerTimestampFieldNumber = 2,
  };
  // repeated .Protocol.EntityState entities = 1;
  int entities_size() const;
  private:
  int _internal_entities_size() const;
  public:
  void clear_entities();
  ::Protocol::EntityState* mutable_entities(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::EntityState >*
      mutable_entities();
  private:
  const ::Protocol::EntityState& _internal_entities(int index) const;
  ::Protocol::EntityState* _internal_add_entities();
  public:
  const ::Protocol::EntityState& entities(int index) const;
  ::Protocol::EntityState* add_entities();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::EntityState >&
      entities() const;

  // int64 serverTimestamp = 2;
  void clear_servertimestamp();
  int64_t servertimestamp() const;
  void set_servertimestamp(int64_t value);
  private:
  int64_t _internal_servertimestamp() const;
  void _internal_set_servertimestamp(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S2C_ENTITY_SNAPSHOT_NOT)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::EntityState > entities_;
    int64_t servertimestamp_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Movement_2eproto;
};
// -------------------------------------------------------------------

class S2C_ENTITY_ENTER_NOT final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S2C_ENTITY_ENTER_NOT) */ {
 public:
  inline S2C_ENTITY_ENTER_NOT() : S2C_ENTITY_ENTER_NOT(nullptr) {}
  ~S2C_ENTITY_ENTER_NOT() override;
  explicit PROTOBUF_CONSTEXPR S2C_ENTITY_ENTER_NOT(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S2C_ENTITY_ENTER_NOT(const S2C_ENTITY_ENTER_NOT& from);
  S2C_ENTITY_ENTER_NOT(S2C_ENTITY_ENTER_NOT&& from) noexcept
    : S2C_ENTITY_ENTER_NOT() {
    *this = ::std::move(from);
  }

  inline S2C_ENTITY_ENTER_NOT& operator=(const S2C_ENTITY_ENTER_NOT& from) {
    CopyFrom(from);
    return *this;
  }
  inline S2C_ENTITY_ENTER_NOT& operator=(S2C_ENTITY_ENTER_NOT&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S2C_ENTITY_ENTER_NOT& default_instance() {
    return *internal_default_instance();
  }
  static inline const S2C_ENTITY_ENTER_NOT* internal_default_instance() {
    return reinterpret_cast<const S2C_ENTITY_ENTER_NOT*>(
               &_S2C_ENTITY_ENTER_NOT_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(S2C_ENTITY_ENTER_NOT& a, S2C_ENTITY_ENTER_NOT& b) {
    a.Swap(&b);
  }
  inline void Swap(S2C_ENTITY_ENTER_NOT* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S2C_ENTITY_ENTER_NOT* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S2C_ENTITY_ENTER_NOT* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S2C_ENTITY_ENTER_NOT>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S2C_ENTITY_ENTER_NOT& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S2C_ENTITY_ENTER_NOT& from) {
    S2C_ENTITY_ENTER_NOT::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S2C_ENTITY_ENTER_NOT* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S2C_ENTITY_ENTER_NOT";
  }
  protected:
  explicit S2C_ENTITY_ENTER_NOT(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEntitiesFieldNumber = 1,
  };
  // repeated .Protocol.EntityState entities = 1;
  int entities_size() const;
  private:
  int _internal_entities_size() const;
  public:
  void clear_entities();
  ::Protocol::EntityState* mutable_entities(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::EntityState >*
      mutable_entities();
  private:
  const ::Protocol::EntityState& _internal_entities(int index) const;
  ::Protocol::EntityState* _internal_add_entities();
  public:
  const ::Protocol::EntityState& entities(int index) const;
  ::Protocol::EntityState* add_entities();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::EntityState >&
      entities() const;

  // @@protoc_insertion_point(class_scope:Protocol.S2C_ENTITY_ENTER_NOT)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::EntityState > entities_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Movement_2eproto;
};
// -------------------------------------------------------------------

class S2C_ENTITY_LEAVE_NOT final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S2C_ENTITY_LEAVE_NOT) */ {
 public:
  inline S2C_ENTITY_LEAVE_NOT() : S2C_ENTITY_LEAVE_NOT(nullptr) {}
  ~S2C_ENTITY_LEAVE_NOT() override;
  explicit PROTOBUF_CONSTEXPR S2C_ENTITY_LEAVE_NOT(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S2C_ENTITY_LEAVE_NOT(const S2C_ENTITY_LEAVE_NOT& from);
  S2C_ENTITY_LEAVE_NOT(S2C_ENTITY_LEAVE_NOT&& from) noexcept
    : S2C_ENTITY_LEAVE_NOT() {
    *this = ::std::move(from);
  }

  inline S2C_ENTITY_LEAVE_NOT& operator=(const S2C_ENTITY_LEAVE_NOT& from) {
    CopyFrom(from);
    return *this;
  }
  inline S2C_ENTITY_LEAVE_NOT& operator=(S2C_ENTITY_LEAVE_NOT&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S2C_ENTITY_LEAVE_NOT& default_instance() {
    return *internal_default_instance();
  }
  static inline const S2C_ENTITY_LEAVE_NOT* internal_default_instance() {
    return reinterpret_cast<const S2C_ENTITY_LEAVE_NOT*>(
               &_S2C_ENTITY_LEAVE_NOT_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(S2C_ENTITY_LEAVE_NOT& a, S2C_ENTITY_LEAVE_NOT& b) {
    a.Swap(&b);
  }
  inline void Swap(S2C_ENTITY_LEAVE_NOT* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S2C_ENTITY_LEAVE_NOT* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S2C_ENTITY_LEAVE_NOT* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S2C_ENTITY_LEAVE_NOT>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S2C_ENTITY_LEAVE_NOT& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S2C_ENTITY_LEAVE_NOT& from) {
    S2C_ENTITY_LEAVE_NOT::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S2C_ENTITY_LEAVE_NOT* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S2C_ENTITY_LEAVE_NOT";
  }
  protected:
  explicit S2C_ENTITY_LEAVE_NOT(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEntityIdsFieldNumber = 1,
  };
  // repeated uint64 entityIds = 1;
  int entityids_size() const;
  private:
  int _internal_entityids_size() const;
  public:
  void clear_entityids();
  private:
  uint64_t _internal_entityids(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >&
      _internal_entityids() const;
  void _internal_add_entityids(uint64_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >*
      _internal_mutable_entityids();
  public:
  uint64_t entityids(int index) const;
  void set_entityids(int index, uint64_t value);
  void add_entityids(uint64_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >&
      entityids() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >*
      mutable_entityids();

  // @@protoc_insertion_point(class_scope:Protocol.S2C_ENTITY_LEAVE_NOT)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t > entityids_;
    mutable std::atomic<int> _entityids_cached_byte_size_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Movement_2eproto;
};
// -------------------------------------------------------------------

class C2S_SPAWN_POSITION_REQ final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:Protocol.C2S_SPAWN_POSITION_REQ) */ {
 public:
  inline C2S_SPAWN_POSITION_REQ() : C2S_SPAWN_POSITION_REQ(nullptr) {}
  explicit PROTOBUF_CONSTEXPR C2S_SPAWN_POSITION_REQ(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C2S_SPAWN_POSITION_REQ(const C2S_SPAWN_POSITION_REQ& from);
  C2S_SPAWN_POSITION_REQ(C2S_SPAWN_POSITION_REQ&& from) noexcept
    : C2S_SPAWN_POSITION_REQ() {
    *this = ::std::move(from);
  }

  inline C2S_SPAWN_POSITION_REQ& operator=(const C2S_SPAWN_POSITION_REQ& from) {
    CopyFrom(from);
    return *this;
  }
  inline C2S_SPAWN_POSITION_REQ& operator=(C2S_SPAWN_POSITION_REQ&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C2S_SPAWN_POSITION_REQ& default_instance() {
    return *internal_default_instance();
  }
  static inline const C2S_SPAWN_POSITION_REQ* internal_default_instance() {
    return reinterpret_cast<const C2S_SPAWN_POSITION_REQ*>(
               &_C2S_SPAWN_POSITION_REQ_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(C2S_SPAWN_POSITION_REQ& a, C2S_SPAWN_POSITION_REQ& b) {
    a.Swap(&b);
  }
  inline void Swap(C2S_SPAWN_POSITION_REQ* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C2S_SPAWN_POSITION_REQ* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C2S_SPAWN_POSITION_REQ* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<C2S_SPAWN_POSITION_REQ>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const C2S_SPAWN_POSITION_REQ& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const C2S_SPAWN_POSITION_REQ& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.C2S_SPAWN_POSITION_REQ";
  }
  protected:
  explicit C2S_SPAWN_POSITION_REQ(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Protocol.C2S_SPAWN_POSITION_REQ)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_Movement_2eproto;
};
// -------------------------------------------------------------------

class S2C_SPAWN_POSITION_RES final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S2C_SPAWN_POSITION_RES) */ {
 public:
  inline S2C_SPAWN_POSITION_RES() : S2C_SPAWN_POSITION_RES(nullptr) {}
  ~S2C_SPAWN_POSITION_RES() override;
  explicit PROTOBUF_CONSTEXPR S2C_SPAWN_POSITION_RES(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S2C_SPAWN_POSITION_RES(const S2C_SPAWN_POSITION_RES& from);
  S2C_SPAWN_POSITION_RES(S2C_SPAWN_POSITION_RES&& from) noexcept
    : S2C_SPAWN_POSITION_RES() {
    *this = ::std::move(from);
  }

  inline S2C_SPAWN_POSITION_RES& operator=(const S2C_SPAWN_POSITION_RES& from) {
    CopyFrom(from);
    return *this;
  }
  inline S2C_SPAWN_POSITION_RES& operator=(S2C_SPAWN_POSITION_RES&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S2C_SPAWN_POSITION_RES& default_instance() {
    return *internal_default_instance();
  }
  static inline const S2C_SPAWN_POSITION_RES* internal_default_instance() {
    return reinterpret_cast<const S2C_SPAWN_POSITION_RES*>(
               &_S2C_SPAWN_POSITION_RES_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(S2C_SPAWN_POSITION_RES& a, S2C_SPAWN_POSITION_RES& b) {
    a.Swap(&b);
  }
  inline void Swap(S2C_SPAWN_POSITION_RES* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S2C_SPAWN_POSITION_RES* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S2C_SPAWN_POSITION_RES* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S2C_SPAWN_POSITION_RES>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S2C_SPAWN_POSITION_RES& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S2C_SPAWN_POSITION_RES& from) {
    S2C_SPAWN_POSITION_RES::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S2C_SPAWN_POSITION_RES* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S2C_SPAWN_POSITION_RES";
  }
  protected:
  explicit S2C_SPAWN_POSITION_RES(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPositionFieldNumber = 1,
    kRotationYawFieldNumber = 2,
  };
  // .Protocol.Vector3 position = 1;
  bool has_position() const;
  private:
  bool _internal_has_position() const;
  public:
  void clear_position();
  const ::Protocol::Vector3& position() const;
  PROTOBUF_NODISCARD ::Protocol::Vector3* release_position();
  ::Protocol::Vector3* mutable_position();
  void set_allocated_position(::Protocol::Vector3* position);
  private:
  const ::Protocol::Vector3& _internal_position() const;
  ::Protocol::Vector3* _internal_mutable_position();
  public:
  void unsafe_arena_set_allocated_position(
      ::Protocol::Vector3* position);
  ::Protocol::Vector3* unsafe_arena_release_position();

  // float rotationYaw = 2;
  void clear_rotationyaw();
  float rotationyaw() const;
  void set_rotationyaw(float value);
  private:
  float _internal_rotationyaw() const;
  void _internal_set_rotationyaw(float value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S2C_SPAWN_POSITION_RES)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::Protocol::Vector3* position_;
    float rotationyaw_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Movement_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// C2S_MOVE_INPUT_NOT

// uint32 sequenceId = 1;
inline void C2S_MOVE_INPUT_NOT::clear_sequenceid() {
  _impl_.sequenceid_ = 0u;
}
inline uint32_t C2S_MOVE_INPUT_NOT::_internal_sequenceid() const {
  return _impl_.sequenceid_;
}
inline uint32_t C2S_MOVE_INPUT_NOT::sequenceid() const {
  // @@protoc_insertion_point(field_get:Protocol.C2S_MOVE_INPUT_NOT.sequenceId)
  return _internal_sequenceid();
}
inline void C2S_MOVE_INPUT_NOT::_internal_set_sequenceid(uint32_t value) {
  
  _impl_.sequenceid_ = value;
}
inline void C2S_MOVE_INPUT_NOT::set_sequenceid(uint32_t value) {
  _internal_set_sequenceid(value);
  // @@protoc_insertion_point(field_set:Protocol.C2S_MOVE_INPUT_NOT.sequenceId)
}

// .Protocol.Vector3 direction = 2;
inline bool C2S_MOVE_INPUT_NOT::_internal_has_direction() const {
  return this != internal_default_instance() && _impl_.direction_ != nullptr;
}
inline bool C2S_MOVE_INPUT_NOT::has_direction() const {
  return _internal_has_direction();
}
inline const ::Protocol::Vector3& C2S_MOVE_INPUT_NOT::_internal_direction() const {
  const ::Protocol::Vector3* p = _impl_.direction_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::Vector3&>(
      ::Protocol::_Vector3_default_instance_);
}
inline const ::Protocol::Vector3& C2S_MOVE_INPUT_NOT::direction() const {
  // @@protoc_insertion_point(field_get:Protocol.C2S_MOVE_INPUT_NOT.direction)
  return _internal_direction();
}
inline void C2S_MOVE_INPUT_NOT::unsafe_arena_set_allocated_direction(
    ::Protocol::Vector3* direction) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.direction_);
  }
  _impl_.direction_ = direction;
  if (direction) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.C2S_MOVE_INPUT_NOT.direction)
}
inline ::Protocol::Vector3* C2S_MOVE_INPUT_NOT::release_direction() {
  
  ::Protocol::Vector3* temp = _impl_.direction_;
  _impl_.direction_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Protocol::Vector3* C2S_MOVE_INPUT_NOT::unsafe_arena_release_direction() {
  // @@protoc_insertion_point(field_release:Protocol.C2S_MOVE_INPUT_NOT.direction)
  
  ::Protocol::Vector3* temp = _impl_.direction_;
  _impl_.direction_ = nullptr;
  return temp;
}
inline ::Protocol::Vector3* C2S_MOVE_INPUT_NOT::_internal_mutable_direction() {
  
  if (_impl_.direction_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::Vector3>(GetArenaForAllocation());
    _impl_.direction_ = p;
  }
  return _impl_.direction_;
}
inline ::Protocol::Vector3* C2S_MOVE_INPUT_NOT::mutable_direction() {
  ::Protocol::Vector3* _msg = _internal_mutable_direction();
  // @@protoc_insertion_point(field_mutable:Protocol.C2S_MOVE_INPUT_NOT.direction)
  return _msg;
}
inline void C2S_MOVE_INPUT_NOT::set_allocated_direction(::Protocol::Vector3* direction) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.direction_);
  }
  if (direction) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(direction));
    if (message_arena != submessage_arena) {
      direction = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, direction, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.direction_ = direction;
  // @@protoc_insertion_point(field_set_allocated:Protocol.C2S_MOVE_INPUT_NOT.direction)
}

// float rotationYaw = 3;
inline void C2S_MOVE_INPUT_NOT::clear_rotationyaw() {
  _impl_.rotationyaw_ = 0;
}
inline float C2S_MOVE_INPUT_NOT::_internal_rotationyaw() const {
  return _impl_.rotationyaw_;
}
inline float C2S_MOVE_INPUT_NOT::rotationyaw() const {
  // @@protoc_insertion_point(field_get:Protocol.C2S_MOVE_INPUT_NOT.rotationYaw)
  return _internal_rotationyaw();
}
inline void C2S_MOVE_INPUT_NOT::_internal_set_rotationyaw(float value) {
  
  _impl_.rotationyaw_ = value;
}
inline void C2S_MOVE_INPUT_NOT::set_rotationyaw(float value) {
  _internal_set_rotationyaw(value);
  // @@protoc_insertion_point(field_set:Protocol.C2S_MOVE_INPUT_NOT.rotationYaw)
}

// int64 clientTimestamp = 4;
inline void C2S_MOVE_INPUT_NOT::clear_clienttimestamp() {
  _impl_.clienttimestamp_ = int64_t{0};
}
inline int64_t C2S_MOVE_INPUT_NOT::_internal_clienttimestamp() const {
  return _impl_.clienttimestamp_;
}
inline int64_t C2S_MOVE_INPUT_NOT::clienttimestamp() const {
  // @@protoc_insertion_point(field_get:Protocol.C2S_MOVE_INPUT_NOT.clientTimestamp)
  return _internal_clienttimestamp();
}
inline void C2S_MOVE_INPUT_NOT::_internal_set_clienttimestamp(int64_t value) {
  
  _impl_.clienttimestamp_ = value;
}
inline void C2S_MOVE_INPUT_NOT::set_clienttimestamp(int64_t value) {
  _internal_set_clienttimestamp(value);
  // @@protoc_insertion_point(field_set:Protocol.C2S_MOVE_INPUT_NOT.clientTimestamp)
}

// float positionZ = 5;
inline void C2S_MOVE_INPUT_NOT::clear_positionz() {
  _impl_.positionz_ = 0;
}
inline float C2S_MOVE_INPUT_NOT::_internal_positionz() const {
  return _impl_.positionz_;
}
inline float C2S_MOVE_INPUT_NOT::positionz() const {
  // @@protoc_insertion_point(field_get:Protocol.C2S_MOVE_INPUT_NOT.positionZ)
  return _internal_positionz();
}
inline void C2S_MOVE_INPUT_NOT::_internal_set_positionz(float value) {
  
  _impl_.positionz_ = value;
}
inline void C2S_MOVE_INPUT_NOT::set_positionz(float value) {
  _internal_set_positionz(value);
  // @@protoc_insertion_point(field_set:Protocol.C2S_MOVE_INPUT_NOT.positionZ)
}

// -------------------------------------------------------------------

// S2C_MOVE_RESULT_NOT

// uint32 sequenceId = 1;
inline void S2C_MOVE_RESULT_NOT::clear_sequenceid() {
  _impl_.sequenceid_ = 0u;
}
inline uint32_t S2C_MOVE_RESULT_NOT::_internal_sequenceid() const {
  return _impl_.sequenceid_;
}
inline uint32_t S2C_MOVE_RESULT_NOT::sequenceid() const {
  // @@protoc_insertion_point(field_get:Protocol.S2C_MOVE_RESULT_NOT.sequenceId)
  return _internal_sequenceid();
}
inline void S2C_MOVE_RESULT_NOT::_internal_set_sequenceid(uint32_t value) {
  
  _impl_.sequenceid_ = value;
}
inline void S2C_MOVE_RESULT_NOT::set_sequenceid(uint32_t value) {
  _internal_set_sequenceid(value);
  // @@protoc_insertion_point(field_set:Protocol.S2C_MOVE_RESULT_NOT.sequenceId)
}

// .Protocol.Vector3 position = 2;
inline bool S2C_MOVE_RESULT_NOT::_internal_has_position() const {
  return this != internal_default_instance() && _impl_.position_ != nullptr;
}
inline bool S2C_MOVE_RESULT_NOT::has_position() const {
  return _internal_has_position();
}
inline const ::Protocol::Vector3& S2C_MOVE_RESULT_NOT::_internal_position() const {
  const ::Protocol::Vector3* p = _impl_.position_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::Vector3&>(
      ::Protocol::_Vector3_default_instance_);
}
inline const ::Protocol::Vector3& S2C_MOVE_RESULT_NOT::position() const {
  // @@protoc_insertion_point(field_get:Protocol.S2C_MOVE_RESULT_NOT.position)
  return _internal_position();
}
inline void S2C_MOVE_RESULT_NOT::unsafe_arena_set_allocated_position(
    ::Protocol::Vector3* position) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.position_);
  }
  _impl_.position_ = position;
  if (position) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.S2C_MOVE_RESULT_NOT.position)
}
inline ::Protocol::Vector3* S2C_MOVE_RESULT_NOT::release_position() {
  
  ::Protocol::Vector3* temp = _impl_.position_;
  _impl_.position_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Protocol::Vector3* S2C_MOVE_RESULT_NOT::unsafe_arena_release_position() {
  // @@protoc_insertion_point(field_release:Protocol.S2C_MOVE_RESULT_NOT.position)
  
  ::Protocol::Vector3* temp = _impl_.position_;
  _impl_.position_ = nullptr;
  return temp;
}
inline ::Protocol::Vector3* S2C_MOVE_RESULT_NOT::_internal_mutable_position() {
  
  if (_impl_.position_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::Vector3>(GetArenaForAllocation());
    _impl_.position_ = p;
  }
  return _impl_.position_;
}
inline ::Protocol::Vector3* S2C_MOVE_RESULT_NOT::mutable_position() {
  ::Protocol::Vector3* _msg = _internal_mutable_position();
  // @@protoc_insertion_point(field_mutable:Protocol.S2C_MOVE_RESULT_NOT.position)
  return _msg;
}
inline void S2C_MOVE_RESULT_NOT::set_allocated_position(::Protocol::Vector3* position) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.position_);
  }
  if (position) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(position));
    if (message_arena != submessage_arena) {
      position = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, position, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.position_ = position;
  // @@protoc_insertion_point(field_set_allocated:Protocol.S2C_MOVE_RESULT_NOT.position)
}

// .Protocol.Vector3 velocity = 3;
inline bool S2C_MOVE_RESULT_NOT::_internal_has_velocity() const {
  return this != internal_default_instance() && _impl_.velocity_ != nullptr;
}
inline bool S2C_MOVE_RESULT_NOT::has_velocity() const {
  return _internal_has_velocity();
}
inline const ::Protocol::Vector3& S2C_MOVE_RESULT_NOT::_internal_velocity() const {
  const ::Protocol::Vector3* p = _impl_.velocity_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::Vector3&>(
      ::Protocol::_Vector3_default_instance_);
}
inline const ::Protocol::Vector3& S2C_MOVE_RESULT_NOT::velocity() const {
  // @@protoc_insertion_point(field_get:Protocol.S2C_MOVE_RESULT_NOT.velocity)
  return _internal_velocity();
}
inline void S2C_MOVE_RESULT_NOT::unsafe_arena_set_allocated_velocity(
    ::Protocol::Vector3* velocity) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.velocity_);
  }
  _impl_.velocity_ = velocity;
  if (velocity) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.S2C_MOVE_RESULT_NOT.velocity)
}
inline ::Protocol::Vector3* S2C_MOVE_RESULT_NOT::release_velocity() {
  
  ::Protocol::Vector3* temp = _impl_.velocity_;
  _impl_.velocity_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Protocol::Vector3* S2C_MOVE_RESULT_NOT::unsafe_arena_release_velocity() {
  // @@protoc_insertion_point(field_release:Protocol.S2C_MOVE_RESULT_NOT.velocity)
  
  ::Protocol::Vector3* temp = _impl_.velocity_;
  _impl_.velocity_ = nullptr;
  return temp;
}
inline ::Protocol::Vector3* S2C_MOVE_RESULT_NOT::_internal_mutable_velocity() {
  
  if (_impl_.velocity_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::Vector3>(GetArenaForAllocation());
    _impl_.velocity_ = p;
  }
  return _impl_.velocity_;
}
inline ::Protocol::Vector3* S2C_MOVE_RESULT_NOT::mutable_velocity() {
  ::Protocol::Vector3* _msg = _internal_mutable_velocity();
  // @@protoc_insertion_point(field_mutable:Protocol.S2C_MOVE_RESULT_NOT.velocity)
  return _msg;
}
inline void S2C_MOVE_RESULT_NOT::set_allocated_velocity(::Protocol::Vector3* velocity) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.velocity_);
  }
  if (velocity) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(velocity));
    if (message_arena != submessage_arena) {
      velocity = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, velocity, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.velocity_ = velocity;
  // @@protoc_insertion_point(field_set_allocated:Protocol.S2C_MOVE_RESULT_NOT.velocity)
}

// float rotationYaw = 4;
inline void S2C_MOVE_RESULT_NOT::clear_rotationyaw() {
  _impl_.rotationyaw_ = 0;
}
inline float S2C_MOVE_RESULT_NOT::_internal_rotationyaw() const {
  return _impl_.rotationyaw_;
}
inline float S2C_MOVE_RESULT_NOT::rotationyaw() const {
  // @@protoc_insertion_point(field_get:Protocol.S2C_MOVE_RESULT_NOT.rotationYaw)
  return _internal_rotationyaw();
}
inline void S2C_MOVE_RESULT_NOT::_internal_set_rotationyaw(float value) {
  
  _impl_.rotationyaw_ = value;
}
inline void S2C_MOVE_RESULT_NOT::set_rotationyaw(float value) {
  _internal_set_rotationyaw(value);
  // @@protoc_insertion_point(field_set:Protocol.S2C_MOVE_RESULT_NOT.rotationYaw)
}

// int64 serverTimestamp = 5;
inline void S2C_MOVE_RESULT_NOT::clear_servertimestamp() {
  _impl_.servertimestamp_ = int64_t{0};
}
inline int64_t S2C_MOVE_RESULT_NOT::_internal_servertimestamp() const {
  return _impl_.servertimestamp_;
}
inline int64_t S2C_MOVE_RESULT_NOT::servertimestamp() const {
  // @@protoc_insertion_point(field_get:Protocol.S2C_MOVE_RESULT_NOT.serverTimestamp)
  return _internal_servertimestamp();
}
inline void S2C_MOVE_RESULT_NOT::_internal_set_servertimestamp(int64_t value) {
  
  _impl_.servertimestamp_ = value;
}
inline void S2C_MOVE_RESULT_NOT::set_servertimestamp(int64_t value) {
  _internal_set_servertimestamp(value);
  // @@protoc_insertion_point(field_set:Protocol.S2C_MOVE_RESULT_NOT.serverTimestamp)
}

// -------------------------------------------------------------------

// S2C_ENTITY_SNAPSHOT_NOT

// repeated .Protocol.EntityState entities = 1;
inline int S2C_ENTITY_SNAPSHOT_NOT::_internal_entities_size() const {
  return _impl_.entities_.size();
}
inline int S2C_ENTITY_SNAPSHOT_NOT::entities_size() const {
  return _internal_entities_size();
}
inline ::Protocol::EntityState* S2C_ENTITY_SNAPSHOT_NOT::mutable_entities(int index) {
  // @@protoc_insertion_point(field_mutable:Protocol.S2C_ENTITY_SNAPSHOT_NOT.entities)
  return _impl_.entities_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::EntityState >*
S2C_ENTITY_SNAPSHOT_NOT::mutable_entities() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.S2C_ENTITY_SNAPSHOT_NOT.entities)
  return &_impl_.entities_;
}
inline const ::Protocol::EntityState& S2C_ENTITY_SNAPSHOT_NOT::_internal_entities(int index) const {
  return _impl_.entities_.Get(index);
}
inline const ::Protocol::EntityState& S2C_ENTITY_SNAPSHOT_NOT::entities(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.S2C_ENTITY_SNAPSHOT_NOT.entities)
  return _internal_entities(index);
}
inline ::Protocol::EntityState* S2C_ENTITY_SNAPSHOT_NOT::_internal_add_entities() {
  return _impl_.entities_.Add();
}
inline ::Protocol::EntityState* S2C_ENTITY_SNAPSHOT_NOT::add_entities() {
  ::Protocol::EntityState* _add = _internal_add_entities();
  // @@protoc_insertion_point(field_add:Protocol.S2C_ENTITY_SNAPSHOT_NOT.entities)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::EntityState >&
S2C_ENTITY_SNAPSHOT_NOT::entities() const {
  // @@protoc_insertion_point(field_list:Protocol.S2C_ENTITY_SNAPSHOT_NOT.entities)
  return _impl_.entities_;
}

// int64 serverTimestamp = 2;
inline void S2C_ENTITY_SNAPSHOT_NOT::clear_servertimestamp() {
  _impl_.servertimestamp_ = int64_t{0};
}
inline int64_t S2C_ENTITY_SNAPSHOT_NOT::_internal_servertimestamp() const {
  return _impl_.servertimestamp_;
}
inline int64_t S2C_ENTITY_SNAPSHOT_NOT::servertimestamp() const {
  // @@protoc_insertion_point(field_get:Protocol.S2C_ENTITY_SNAPSHOT_NOT.serverTimestamp)
  return _internal_servertimestamp();
}
inline void S2C_ENTITY_SNAPSHOT_NOT::_internal_set_servertimestamp(int64_t value) {
  
  _impl_.servertimestamp_ = value;
}
inline void S2C_ENTITY_SNAPSHOT_NOT::set_servertimestamp(int64_t value) {
  _internal_set_servertimestamp(value);
  // @@protoc_insertion_point(field_set:Protocol.S2C_ENTITY_SNAPSHOT_NOT.serverTimestamp)
}

// -------------------------------------------------------------------

// S2C_ENTITY_ENTER_NOT

// repeated .Protocol.EntityState entities = 1;
inline int S2C_ENTITY_ENTER_NOT::_internal_entities_size() const {
  return _impl_.entities_.size();
}
inline int S2C_ENTITY_ENTER_NOT::entities_size() const {
  return _internal_entities_size();
}
inline ::Protocol::EntityState* S2C_ENTITY_ENTER_NOT::mutable_entities(int index) {
  // @@protoc_insertion_point(field_mutable:Protocol.S2C_ENTITY_ENTER_NOT.entities)
  return _impl_.entities_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::EntityState >*
S2C_ENTITY_ENTER_NOT::mutable_entities() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.S2C_ENTITY_ENTER_NOT.entities)
  return &_impl_.entities_;
}
inline const ::Protocol::EntityState& S2C_ENTITY_ENTER_NOT::_internal_entities(int index) const {
  return _impl_.entities_.Get(index);
}
inline const ::Protocol::EntityState& S2C_ENTITY_ENTER_NOT::entities(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.S2C_ENTITY_ENTER_NOT.entities)
  return _internal_entities(index);
}
inline ::Protocol::EntityState* S2C_ENTITY_ENTER_NOT::_internal_add_entities() {
  return _impl_.entities_.Add();
}
inline ::Protocol::EntityState* S2C_ENTITY_ENTER_NOT::add_entities() {
  ::Protocol::EntityState* _add = _internal_add_entities();
  // @@protoc_insertion_point(field_add:Protocol.S2C_ENTITY_ENTER_NOT.entities)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::EntityState >&
S2C_ENTITY_ENTER_NOT::entities() const {
  // @@protoc_insertion_point(field_list:Protocol.S2C_ENTITY_ENTER_NOT.entities)
  return _impl_.entities_;
}

// -------------------------------------------------------------------

// S2C_ENTITY_LEAVE_NOT

// repeated uint64 entityIds = 1;
inline int S2C_ENTITY_LEAVE_NOT::_internal_entityids_size() const {
  return _impl_.entityids_.size();
}
inline int S2C_ENTITY_LEAVE_NOT::entityids_size() const {
  return _internal_entityids_size();
}
inline void S2C_ENTITY_LEAVE_NOT::clear_entityids() {
  _impl_.entityids_.Clear();
}
inline uint64_t S2C_ENTITY_LEAVE_NOT::_internal_entityids(int index) const {
  return _impl_.entityids_.Get(index);
}
inline uint64_t S2C_ENTITY_LEAVE_NOT::entityids(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.S2C_ENTITY_LEAVE_NOT.entityIds)
  return _internal_entityids(index);
}
inline void S2C_ENTITY_LEAVE_NOT::set_entityids(int index, uint64_t value) {
  _impl_.entityids_.Set(index, value);
  // @@protoc_insertion_point(field_set:Protocol.S2C_ENTITY_LEAVE_NOT.entityIds)
}
inline void S2C_ENTITY_LEAVE_NOT::_internal_add_entityids(uint64_t value) {
  _impl_.entityids_.Add(value);
}
inline void S2C_ENTITY_LEAVE_NOT::add_entityids(uint64_t value) {
  _internal_add_entityids(value);
  // @@protoc_insertion_point(field_add:Protocol.S2C_ENTITY_LEAVE_NOT.entityIds)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >&
S2C_ENTITY_LEAVE_NOT::_internal_entityids() const {
  return _impl_.entityids_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >&
S2C_ENTITY_LEAVE_NOT::entityids() const {
  // @@protoc_insertion_point(field_list:Protocol.S2C_ENTITY_LEAVE_NOT.entityIds)
  return _internal_entityids();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >*
S2C_ENTITY_LEAVE_NOT::_internal_mutable_entityids() {
  return &_impl_.entityids_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >*
S2C_ENTITY_LEAVE_NOT::mutable_entityids() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.S2C_ENTITY_LEAVE_NOT.entityIds)
  return _internal_mutable_entityids();
}

// -------------------------------------------------------------------

// C2S_SPAWN_POSITION_REQ

// -------------------------------------------------------------------

// S2C_SPAWN_POSITION_RES

// .Protocol.Vector3 position = 1;
inline bool S2C_SPAWN_POSITION_RES::_internal_has_position() const {
  return this != internal_default_instance() && _impl_.position_ != nullptr;
}
inline bool S2C_SPAWN_POSITION_RES::has_position() const {
  return _internal_has_position();
}
inline const ::Protocol::Vector3& S2C_SPAWN_POSITION_RES::_internal_position() const {
  const ::Protocol::Vector3* p = _impl_.position_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::Vector3&>(
      ::Protocol::_Vector3_default_instance_);
}
inline const ::Protocol::Vector3& S2C_SPAWN_POSITION_RES::position() const {
  // @@protoc_insertion_point(field_get:Protocol.S2C_SPAWN_POSITION_RES.position)
  return _internal_position();
}
inline void S2C_SPAWN_POSITION_RES::unsafe_arena_set_allocated_position(
    ::Protocol::Vector3* position) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.position_);
  }
  _impl_.position_ = position;
  if (position) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.S2C_SPAWN_POSITION_RES.position)
}
inline ::Protocol::Vector3* S2C_SPAWN_POSITION_RES::release_position() {
  
  ::Protocol::Vector3* temp = _impl_.position_;
  _impl_.position_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Protocol::Vector3* S2C_SPAWN_POSITION_RES::unsafe_arena_release_position() {
  // @@protoc_insertion_point(field_release:Protocol.S2C_SPAWN_POSITION_RES.position)
  
  ::Protocol::Vector3* temp = _impl_.position_;
  _impl_.position_ = nullptr;
  return temp;
}
inline ::Protocol::Vector3* S2C_SPAWN_POSITION_RES::_internal_mutable_position() {
  
  if (_impl_.position_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::Vector3>(GetArenaForAllocation());
    _impl_.position_ = p;
  }
  return _impl_.position_;
}
inline ::Protocol::Vector3* S2C_SPAWN_POSITION_RES::mutable_position() {
  ::Protocol::Vector3* _msg = _internal_mutable_position();
  // @@protoc_insertion_point(field_mutable:Protocol.S2C_SPAWN_POSITION_RES.position)
  return _msg;
}
inline void S2C_SPAWN_POSITION_RES::set_allocated_position(::Protocol::Vector3* position) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.position_);
  }
  if (position) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(position));
    if (message_arena != submessage_arena) {
      position = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, position, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.position_ = position;
  // @@protoc_insertion_point(field_set_allocated:Protocol.S2C_SPAWN_POSITION_RES.position)
}

// float rotationYaw = 2;
inline void S2C_SPAWN_POSITION_RES::clear_rotationyaw() {
  _impl_.rotationyaw_ = 0;
}
inline float S2C_SPAWN_POSITION_RES::_internal_rotationyaw() const {
  return _impl_.rotationyaw_;
}
inline float S2C_SPAWN_POSITION_RES::rotationyaw() const {
  // @@protoc_insertion_point(field_get:Protocol.S2C_SPAWN_POSITION_RES.rotationYaw)
  return _internal_rotationyaw();
}
inline void S2C_SPAWN_POSITION_RES::_internal_set_rotationyaw(float value) {
  
  _impl_.rotationyaw_ = value;
}
inline void S2C_SPAWN_POSITION_RES::set_rotationyaw(float value) {
  _internal_set_rotationyaw(value);
  // @@protoc_insertion_point(field_set:Protocol.S2C_SPAWN_POSITION_RES.rotationYaw)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Movement_2eproto
