// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerHeartbeat.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ServerHeartbeat_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ServerHeartbeat_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "PacketOption.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ServerHeartbeat_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ServerHeartbeat_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ServerHeartbeat_2eproto;
namespace Protocol {
class S2S_HEARTBEAT_REQ;
struct S2S_HEARTBEAT_REQDefaultTypeInternal;
extern S2S_HEARTBEAT_REQDefaultTypeInternal _S2S_HEARTBEAT_REQ_default_instance_;
class S2S_HEARTBEAT_RES;
struct S2S_HEARTBEAT_RESDefaultTypeInternal;
extern S2S_HEARTBEAT_RESDefaultTypeInternal _S2S_HEARTBEAT_RES_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::S2S_HEARTBEAT_REQ* Arena::CreateMaybeMessage<::Protocol::S2S_HEARTBEAT_REQ>(Arena*);
template<> ::Protocol::S2S_HEARTBEAT_RES* Arena::CreateMaybeMessage<::Protocol::S2S_HEARTBEAT_RES>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class S2S_HEARTBEAT_REQ final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S2S_HEARTBEAT_REQ) */ {
 public:
  inline S2S_HEARTBEAT_REQ() : S2S_HEARTBEAT_REQ(nullptr) {}
  ~S2S_HEARTBEAT_REQ() override;
  explicit PROTOBUF_CONSTEXPR S2S_HEARTBEAT_REQ(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S2S_HEARTBEAT_REQ(const S2S_HEARTBEAT_REQ& from);
  S2S_HEARTBEAT_REQ(S2S_HEARTBEAT_REQ&& from) noexcept
    : S2S_HEARTBEAT_REQ() {
    *this = ::std::move(from);
  }

  inline S2S_HEARTBEAT_REQ& operator=(const S2S_HEARTBEAT_REQ& from) {
    CopyFrom(from);
    return *this;
  }
  inline S2S_HEARTBEAT_REQ& operator=(S2S_HEARTBEAT_REQ&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S2S_HEARTBEAT_REQ& default_instance() {
    return *internal_default_instance();
  }
  static inline const S2S_HEARTBEAT_REQ* internal_default_instance() {
    return reinterpret_cast<const S2S_HEARTBEAT_REQ*>(
               &_S2S_HEARTBEAT_REQ_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(S2S_HEARTBEAT_REQ& a, S2S_HEARTBEAT_REQ& b) {
    a.Swap(&b);
  }
  inline void Swap(S2S_HEARTBEAT_REQ* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S2S_HEARTBEAT_REQ* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S2S_HEARTBEAT_REQ* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S2S_HEARTBEAT_REQ>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S2S_HEARTBEAT_REQ& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S2S_HEARTBEAT_REQ& from) {
    S2S_HEARTBEAT_REQ::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S2S_HEARTBEAT_REQ* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S2S_HEARTBEAT_REQ";
  }
  protected:
  explicit S2S_HEARTBEAT_REQ(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTimestampFieldNumber = 2,
    kServerIdFieldNumber = 1,
    kSessionCountFieldNumber = 3,
    kStatusFieldNumber = 4,
  };
  // int64 timestamp = 2;
  void clear_timestamp();
  int64_t timestamp() const;
  void set_timestamp(int64_t value);
  private:
  int64_t _internal_timestamp() const;
  void _internal_set_timestamp(int64_t value);
  public:

  // int32 serverId = 1;
  void clear_serverid();
  int32_t serverid() const;
  void set_serverid(int32_t value);
  private:
  int32_t _internal_serverid() const;
  void _internal_set_serverid(int32_t value);
  public:

  // int32 sessionCount = 3;
  void clear_sessioncount();
  int32_t sessioncount() const;
  void set_sessioncount(int32_t value);
  private:
  int32_t _internal_sessioncount() const;
  void _internal_set_sessioncount(int32_t value);
  public:

  // int32 status = 4;
  void clear_status();
  int32_t status() const;
  void set_status(int32_t value);
  private:
  int32_t _internal_status() const;
  void _internal_set_status(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S2S_HEARTBEAT_REQ)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t timestamp_;
    int32_t serverid_;
    int32_t sessioncount_;
    int32_t status_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ServerHeartbeat_2eproto;
};
// -------------------------------------------------------------------

class S2S_HEARTBEAT_RES final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S2S_HEARTBEAT_RES) */ {
 public:
  inline S2S_HEARTBEAT_RES() : S2S_HEARTBEAT_RES(nullptr) {}
  ~S2S_HEARTBEAT_RES() override;
  explicit PROTOBUF_CONSTEXPR S2S_HEARTBEAT_RES(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S2S_HEARTBEAT_RES(const S2S_HEARTBEAT_RES& from);
  S2S_HEARTBEAT_RES(S2S_HEARTBEAT_RES&& from) noexcept
    : S2S_HEARTBEAT_RES() {
    *this = ::std::move(from);
  }

  inline S2S_HEARTBEAT_RES& operator=(const S2S_HEARTBEAT_RES& from) {
    CopyFrom(from);
    return *this;
  }
  inline S2S_HEARTBEAT_RES& operator=(S2S_HEARTBEAT_RES&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S2S_HEARTBEAT_RES& default_instance() {
    return *internal_default_instance();
  }
  static inline const S2S_HEARTBEAT_RES* internal_default_instance() {
    return reinterpret_cast<const S2S_HEARTBEAT_RES*>(
               &_S2S_HEARTBEAT_RES_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(S2S_HEARTBEAT_RES& a, S2S_HEARTBEAT_RES& b) {
    a.Swap(&b);
  }
  inline void Swap(S2S_HEARTBEAT_RES* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S2S_HEARTBEAT_RES* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S2S_HEARTBEAT_RES* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S2S_HEARTBEAT_RES>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S2S_HEARTBEAT_RES& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S2S_HEARTBEAT_RES& from) {
    S2S_HEARTBEAT_RES::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S2S_HEARTBEAT_RES* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S2S_HEARTBEAT_RES";
  }
  protected:
  explicit S2S_HEARTBEAT_RES(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTimestampFieldNumber = 1,
    kAcceptedFieldNumber = 2,
  };
  // int64 timestamp = 1;
  void clear_timestamp();
  int64_t timestamp() const;
  void set_timestamp(int64_t value);
  private:
  int64_t _internal_timestamp() const;
  void _internal_set_timestamp(int64_t value);
  public:

  // bool accepted = 2;
  void clear_accepted();
  bool accepted() const;
  void set_accepted(bool value);
  private:
  bool _internal_accepted() const;
  void _internal_set_accepted(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S2S_HEARTBEAT_RES)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t timestamp_;
    bool accepted_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ServerHeartbeat_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// S2S_HEARTBEAT_REQ

// int32 serverId = 1;
inline void S2S_HEARTBEAT_REQ::clear_serverid() {
  _impl_.serverid_ = 0;
}
inline int32_t S2S_HEARTBEAT_REQ::_internal_serverid() const {
  return _impl_.serverid_;
}
inline int32_t S2S_HEARTBEAT_REQ::serverid() const {
  // @@protoc_insertion_point(field_get:Protocol.S2S_HEARTBEAT_REQ.serverId)
  return _internal_serverid();
}
inline void S2S_HEARTBEAT_REQ::_internal_set_serverid(int32_t value) {
  
  _impl_.serverid_ = value;
}
inline void S2S_HEARTBEAT_REQ::set_serverid(int32_t value) {
  _internal_set_serverid(value);
  // @@protoc_insertion_point(field_set:Protocol.S2S_HEARTBEAT_REQ.serverId)
}

// int64 timestamp = 2;
inline void S2S_HEARTBEAT_REQ::clear_timestamp() {
  _impl_.timestamp_ = int64_t{0};
}
inline int64_t S2S_HEARTBEAT_REQ::_internal_timestamp() const {
  return _impl_.timestamp_;
}
inline int64_t S2S_HEARTBEAT_REQ::timestamp() const {
  // @@protoc_insertion_point(field_get:Protocol.S2S_HEARTBEAT_REQ.timestamp)
  return _internal_timestamp();
}
inline void S2S_HEARTBEAT_REQ::_internal_set_timestamp(int64_t value) {
  
  _impl_.timestamp_ = value;
}
inline void S2S_HEARTBEAT_REQ::set_timestamp(int64_t value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:Protocol.S2S_HEARTBEAT_REQ.timestamp)
}

// int32 sessionCount = 3;
inline void S2S_HEARTBEAT_REQ::clear_sessioncount() {
  _impl_.sessioncount_ = 0;
}
inline int32_t S2S_HEARTBEAT_REQ::_internal_sessioncount() const {
  return _impl_.sessioncount_;
}
inline int32_t S2S_HEARTBEAT_REQ::sessioncount() const {
  // @@protoc_insertion_point(field_get:Protocol.S2S_HEARTBEAT_REQ.sessionCount)
  return _internal_sessioncount();
}
inline void S2S_HEARTBEAT_REQ::_internal_set_sessioncount(int32_t value) {
  
  _impl_.sessioncount_ = value;
}
inline void S2S_HEARTBEAT_REQ::set_sessioncount(int32_t value) {
  _internal_set_sessioncount(value);
  // @@protoc_insertion_point(field_set:Protocol.S2S_HEARTBEAT_REQ.sessionCount)
}

// int32 status = 4;
inline void S2S_HEARTBEAT_REQ::clear_status() {
  _impl_.status_ = 0;
}
inline int32_t S2S_HEARTBEAT_REQ::_internal_status() const {
  return _impl_.status_;
}
inline int32_t S2S_HEARTBEAT_REQ::status() const {
  // @@protoc_insertion_point(field_get:Protocol.S2S_HEARTBEAT_REQ.status)
  return _internal_status();
}
inline void S2S_HEARTBEAT_REQ::_internal_set_status(int32_t value) {
  
  _impl_.status_ = value;
}
inline void S2S_HEARTBEAT_REQ::set_status(int32_t value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:Protocol.S2S_HEARTBEAT_REQ.status)
}

// -------------------------------------------------------------------

// S2S_HEARTBEAT_RES

// int64 timestamp = 1;
inline void S2S_HEARTBEAT_RES::clear_timestamp() {
  _impl_.timestamp_ = int64_t{0};
}
inline int64_t S2S_HEARTBEAT_RES::_internal_timestamp() const {
  return _impl_.timestamp_;
}
inline int64_t S2S_HEARTBEAT_RES::timestamp() const {
  // @@protoc_insertion_point(field_get:Protocol.S2S_HEARTBEAT_RES.timestamp)
  return _internal_timestamp();
}
inline void S2S_HEARTBEAT_RES::_internal_set_timestamp(int64_t value) {
  
  _impl_.timestamp_ = value;
}
inline void S2S_HEARTBEAT_RES::set_timestamp(int64_t value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:Protocol.S2S_HEARTBEAT_RES.timestamp)
}

// bool accepted = 2;
inline void S2S_HEARTBEAT_RES::clear_accepted() {
  _impl_.accepted_ = false;
}
inline bool S2S_HEARTBEAT_RES::_internal_accepted() const {
  return _impl_.accepted_;
}
inline bool S2S_HEARTBEAT_RES::accepted() const {
  // @@protoc_insertion_point(field_get:Protocol.S2S_HEARTBEAT_RES.accepted)
  return _internal_accepted();
}
inline void S2S_HEARTBEAT_RES::_internal_set_accepted(bool value) {
  
  _impl_.accepted_ = value;
}
inline void S2S_HEARTBEAT_RES::set_accepted(bool value) {
  _internal_set_accepted(value);
  // @@protoc_insertion_point(field_set:Protocol.S2S_HEARTBEAT_RES.accepted)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ServerHeartbeat_2eproto
