// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: World.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_World_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_World_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_bases.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Enum.pb.h"
#include "Struct.pb.h"
#include "PacketOption.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_World_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_World_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_World_2eproto;
namespace Protocol {
class C2S_WORLD_LIST_REQ;
struct C2S_WORLD_LIST_REQDefaultTypeInternal;
extern C2S_WORLD_LIST_REQDefaultTypeInternal _C2S_WORLD_LIST_REQ_default_instance_;
class C2S_WORLD_SELECT_REQ;
struct C2S_WORLD_SELECT_REQDefaultTypeInternal;
extern C2S_WORLD_SELECT_REQDefaultTypeInternal _C2S_WORLD_SELECT_REQ_default_instance_;
class S2C_WORLD_LIST_RES;
struct S2C_WORLD_LIST_RESDefaultTypeInternal;
extern S2C_WORLD_LIST_RESDefaultTypeInternal _S2C_WORLD_LIST_RES_default_instance_;
class S2C_WORLD_SELECT_RES;
struct S2C_WORLD_SELECT_RESDefaultTypeInternal;
extern S2C_WORLD_SELECT_RESDefaultTypeInternal _S2C_WORLD_SELECT_RES_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::C2S_WORLD_LIST_REQ* Arena::CreateMaybeMessage<::Protocol::C2S_WORLD_LIST_REQ>(Arena*);
template<> ::Protocol::C2S_WORLD_SELECT_REQ* Arena::CreateMaybeMessage<::Protocol::C2S_WORLD_SELECT_REQ>(Arena*);
template<> ::Protocol::S2C_WORLD_LIST_RES* Arena::CreateMaybeMessage<::Protocol::S2C_WORLD_LIST_RES>(Arena*);
template<> ::Protocol::S2C_WORLD_SELECT_RES* Arena::CreateMaybeMessage<::Protocol::S2C_WORLD_SELECT_RES>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class C2S_WORLD_LIST_REQ final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:Protocol.C2S_WORLD_LIST_REQ) */ {
 public:
  inline C2S_WORLD_LIST_REQ() : C2S_WORLD_LIST_REQ(nullptr) {}
  explicit PROTOBUF_CONSTEXPR C2S_WORLD_LIST_REQ(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C2S_WORLD_LIST_REQ(const C2S_WORLD_LIST_REQ& from);
  C2S_WORLD_LIST_REQ(C2S_WORLD_LIST_REQ&& from) noexcept
    : C2S_WORLD_LIST_REQ() {
    *this = ::std::move(from);
  }

  inline C2S_WORLD_LIST_REQ& operator=(const C2S_WORLD_LIST_REQ& from) {
    CopyFrom(from);
    return *this;
  }
  inline C2S_WORLD_LIST_REQ& operator=(C2S_WORLD_LIST_REQ&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C2S_WORLD_LIST_REQ& default_instance() {
    return *internal_default_instance();
  }
  static inline const C2S_WORLD_LIST_REQ* internal_default_instance() {
    return reinterpret_cast<const C2S_WORLD_LIST_REQ*>(
               &_C2S_WORLD_LIST_REQ_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(C2S_WORLD_LIST_REQ& a, C2S_WORLD_LIST_REQ& b) {
    a.Swap(&b);
  }
  inline void Swap(C2S_WORLD_LIST_REQ* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C2S_WORLD_LIST_REQ* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C2S_WORLD_LIST_REQ* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<C2S_WORLD_LIST_REQ>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const C2S_WORLD_LIST_REQ& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const C2S_WORLD_LIST_REQ& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.C2S_WORLD_LIST_REQ";
  }
  protected:
  explicit C2S_WORLD_LIST_REQ(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:Protocol.C2S_WORLD_LIST_REQ)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_World_2eproto;
};
// -------------------------------------------------------------------

class S2C_WORLD_LIST_RES final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S2C_WORLD_LIST_RES) */ {
 public:
  inline S2C_WORLD_LIST_RES() : S2C_WORLD_LIST_RES(nullptr) {}
  ~S2C_WORLD_LIST_RES() override;
  explicit PROTOBUF_CONSTEXPR S2C_WORLD_LIST_RES(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S2C_WORLD_LIST_RES(const S2C_WORLD_LIST_RES& from);
  S2C_WORLD_LIST_RES(S2C_WORLD_LIST_RES&& from) noexcept
    : S2C_WORLD_LIST_RES() {
    *this = ::std::move(from);
  }

  inline S2C_WORLD_LIST_RES& operator=(const S2C_WORLD_LIST_RES& from) {
    CopyFrom(from);
    return *this;
  }
  inline S2C_WORLD_LIST_RES& operator=(S2C_WORLD_LIST_RES&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S2C_WORLD_LIST_RES& default_instance() {
    return *internal_default_instance();
  }
  static inline const S2C_WORLD_LIST_RES* internal_default_instance() {
    return reinterpret_cast<const S2C_WORLD_LIST_RES*>(
               &_S2C_WORLD_LIST_RES_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(S2C_WORLD_LIST_RES& a, S2C_WORLD_LIST_RES& b) {
    a.Swap(&b);
  }
  inline void Swap(S2C_WORLD_LIST_RES* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S2C_WORLD_LIST_RES* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S2C_WORLD_LIST_RES* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S2C_WORLD_LIST_RES>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S2C_WORLD_LIST_RES& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S2C_WORLD_LIST_RES& from) {
    S2C_WORLD_LIST_RES::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S2C_WORLD_LIST_RES* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S2C_WORLD_LIST_RES";
  }
  protected:
  explicit S2C_WORLD_LIST_RES(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kWorldsFieldNumber = 1,
  };
  // repeated .Protocol.WorldServerInfo worlds = 1;
  int worlds_size() const;
  private:
  int _internal_worlds_size() const;
  public:
  void clear_worlds();
  ::Protocol::WorldServerInfo* mutable_worlds(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::WorldServerInfo >*
      mutable_worlds();
  private:
  const ::Protocol::WorldServerInfo& _internal_worlds(int index) const;
  ::Protocol::WorldServerInfo* _internal_add_worlds();
  public:
  const ::Protocol::WorldServerInfo& worlds(int index) const;
  ::Protocol::WorldServerInfo* add_worlds();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::WorldServerInfo >&
      worlds() const;

  // @@protoc_insertion_point(class_scope:Protocol.S2C_WORLD_LIST_RES)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::WorldServerInfo > worlds_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_World_2eproto;
};
// -------------------------------------------------------------------

class C2S_WORLD_SELECT_REQ final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.C2S_WORLD_SELECT_REQ) */ {
 public:
  inline C2S_WORLD_SELECT_REQ() : C2S_WORLD_SELECT_REQ(nullptr) {}
  ~C2S_WORLD_SELECT_REQ() override;
  explicit PROTOBUF_CONSTEXPR C2S_WORLD_SELECT_REQ(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C2S_WORLD_SELECT_REQ(const C2S_WORLD_SELECT_REQ& from);
  C2S_WORLD_SELECT_REQ(C2S_WORLD_SELECT_REQ&& from) noexcept
    : C2S_WORLD_SELECT_REQ() {
    *this = ::std::move(from);
  }

  inline C2S_WORLD_SELECT_REQ& operator=(const C2S_WORLD_SELECT_REQ& from) {
    CopyFrom(from);
    return *this;
  }
  inline C2S_WORLD_SELECT_REQ& operator=(C2S_WORLD_SELECT_REQ&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C2S_WORLD_SELECT_REQ& default_instance() {
    return *internal_default_instance();
  }
  static inline const C2S_WORLD_SELECT_REQ* internal_default_instance() {
    return reinterpret_cast<const C2S_WORLD_SELECT_REQ*>(
               &_C2S_WORLD_SELECT_REQ_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(C2S_WORLD_SELECT_REQ& a, C2S_WORLD_SELECT_REQ& b) {
    a.Swap(&b);
  }
  inline void Swap(C2S_WORLD_SELECT_REQ* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C2S_WORLD_SELECT_REQ* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C2S_WORLD_SELECT_REQ* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<C2S_WORLD_SELECT_REQ>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const C2S_WORLD_SELECT_REQ& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const C2S_WORLD_SELECT_REQ& from) {
    C2S_WORLD_SELECT_REQ::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C2S_WORLD_SELECT_REQ* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.C2S_WORLD_SELECT_REQ";
  }
  protected:
  explicit C2S_WORLD_SELECT_REQ(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kWorldIdFieldNumber = 1,
  };
  // int32 worldId = 1;
  void clear_worldid();
  int32_t worldid() const;
  void set_worldid(int32_t value);
  private:
  int32_t _internal_worldid() const;
  void _internal_set_worldid(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.C2S_WORLD_SELECT_REQ)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t worldid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_World_2eproto;
};
// -------------------------------------------------------------------

class S2C_WORLD_SELECT_RES final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S2C_WORLD_SELECT_RES) */ {
 public:
  inline S2C_WORLD_SELECT_RES() : S2C_WORLD_SELECT_RES(nullptr) {}
  ~S2C_WORLD_SELECT_RES() override;
  explicit PROTOBUF_CONSTEXPR S2C_WORLD_SELECT_RES(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S2C_WORLD_SELECT_RES(const S2C_WORLD_SELECT_RES& from);
  S2C_WORLD_SELECT_RES(S2C_WORLD_SELECT_RES&& from) noexcept
    : S2C_WORLD_SELECT_RES() {
    *this = ::std::move(from);
  }

  inline S2C_WORLD_SELECT_RES& operator=(const S2C_WORLD_SELECT_RES& from) {
    CopyFrom(from);
    return *this;
  }
  inline S2C_WORLD_SELECT_RES& operator=(S2C_WORLD_SELECT_RES&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S2C_WORLD_SELECT_RES& default_instance() {
    return *internal_default_instance();
  }
  static inline const S2C_WORLD_SELECT_RES* internal_default_instance() {
    return reinterpret_cast<const S2C_WORLD_SELECT_RES*>(
               &_S2C_WORLD_SELECT_RES_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(S2C_WORLD_SELECT_RES& a, S2C_WORLD_SELECT_RES& b) {
    a.Swap(&b);
  }
  inline void Swap(S2C_WORLD_SELECT_RES* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S2C_WORLD_SELECT_RES* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S2C_WORLD_SELECT_RES* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S2C_WORLD_SELECT_RES>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S2C_WORLD_SELECT_RES& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S2C_WORLD_SELECT_RES& from) {
    S2C_WORLD_SELECT_RES::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S2C_WORLD_SELECT_RES* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S2C_WORLD_SELECT_RES";
  }
  protected:
  explicit S2C_WORLD_SELECT_RES(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResultFieldNumber = 1,
  };
  // .Protocol.eWorldSelectResult result = 1;
  void clear_result();
  ::Protocol::eWorldSelectResult result() const;
  void set_result(::Protocol::eWorldSelectResult value);
  private:
  ::Protocol::eWorldSelectResult _internal_result() const;
  void _internal_set_result(::Protocol::eWorldSelectResult value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S2C_WORLD_SELECT_RES)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int result_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_World_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// C2S_WORLD_LIST_REQ

// -------------------------------------------------------------------

// S2C_WORLD_LIST_RES

// repeated .Protocol.WorldServerInfo worlds = 1;
inline int S2C_WORLD_LIST_RES::_internal_worlds_size() const {
  return _impl_.worlds_.size();
}
inline int S2C_WORLD_LIST_RES::worlds_size() const {
  return _internal_worlds_size();
}
inline ::Protocol::WorldServerInfo* S2C_WORLD_LIST_RES::mutable_worlds(int index) {
  // @@protoc_insertion_point(field_mutable:Protocol.S2C_WORLD_LIST_RES.worlds)
  return _impl_.worlds_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::WorldServerInfo >*
S2C_WORLD_LIST_RES::mutable_worlds() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.S2C_WORLD_LIST_RES.worlds)
  return &_impl_.worlds_;
}
inline const ::Protocol::WorldServerInfo& S2C_WORLD_LIST_RES::_internal_worlds(int index) const {
  return _impl_.worlds_.Get(index);
}
inline const ::Protocol::WorldServerInfo& S2C_WORLD_LIST_RES::worlds(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.S2C_WORLD_LIST_RES.worlds)
  return _internal_worlds(index);
}
inline ::Protocol::WorldServerInfo* S2C_WORLD_LIST_RES::_internal_add_worlds() {
  return _impl_.worlds_.Add();
}
inline ::Protocol::WorldServerInfo* S2C_WORLD_LIST_RES::add_worlds() {
  ::Protocol::WorldServerInfo* _add = _internal_add_worlds();
  // @@protoc_insertion_point(field_add:Protocol.S2C_WORLD_LIST_RES.worlds)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::WorldServerInfo >&
S2C_WORLD_LIST_RES::worlds() const {
  // @@protoc_insertion_point(field_list:Protocol.S2C_WORLD_LIST_RES.worlds)
  return _impl_.worlds_;
}

// -------------------------------------------------------------------

// C2S_WORLD_SELECT_REQ

// int32 worldId = 1;
inline void C2S_WORLD_SELECT_REQ::clear_worldid() {
  _impl_.worldid_ = 0;
}
inline int32_t C2S_WORLD_SELECT_REQ::_internal_worldid() const {
  return _impl_.worldid_;
}
inline int32_t C2S_WORLD_SELECT_REQ::worldid() const {
  // @@protoc_insertion_point(field_get:Protocol.C2S_WORLD_SELECT_REQ.worldId)
  return _internal_worldid();
}
inline void C2S_WORLD_SELECT_REQ::_internal_set_worldid(int32_t value) {
  
  _impl_.worldid_ = value;
}
inline void C2S_WORLD_SELECT_REQ::set_worldid(int32_t value) {
  _internal_set_worldid(value);
  // @@protoc_insertion_point(field_set:Protocol.C2S_WORLD_SELECT_REQ.worldId)
}

// -------------------------------------------------------------------

// S2C_WORLD_SELECT_RES

// .Protocol.eWorldSelectResult result = 1;
inline void S2C_WORLD_SELECT_RES::clear_result() {
  _impl_.result_ = 0;
}
inline ::Protocol::eWorldSelectResult S2C_WORLD_SELECT_RES::_internal_result() const {
  return static_cast< ::Protocol::eWorldSelectResult >(_impl_.result_);
}
inline ::Protocol::eWorldSelectResult S2C_WORLD_SELECT_RES::result() const {
  // @@protoc_insertion_point(field_get:Protocol.S2C_WORLD_SELECT_RES.result)
  return _internal_result();
}
inline void S2C_WORLD_SELECT_RES::_internal_set_result(::Protocol::eWorldSelectResult value) {
  
  _impl_.result_ = value;
}
inline void S2C_WORLD_SELECT_RES::set_result(::Protocol::eWorldSelectResult value) {
  _internal_set_result(value);
  // @@protoc_insertion_point(field_set:Protocol.S2C_WORLD_SELECT_RES.result)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_World_2eproto
