// =============================================================================
// AUTO-GENERATED FILE - DO NOT EDIT
// This file is generated by PacketGenerator. Any manual changes will be lost.
// =============================================================================
#pragma once
#include "HeartbeatPacketHandler.h"
#include "LoginPacketHandler.h"
#include "WorldPacketHandler.h"

#include "SessionValidator.h"

class PacketServiceTypeHandler
{
public:

	using PacketServiceTypeHandle = std::function<bool(const uint16, const uint16, const byte*, const PacketSessionRef&)>;

	static constexpr uint16 GET_SERVICE_TYPE(const uint32 packetId) { return (packetId >> 16) & 0x0000FFFF; }
	static constexpr uint16 GET_PACKET_ID(const uint32 packetId) { return packetId & 0x0000FFFF; }

	static void Init()
	{
		HeartbeatPacketHandler::Init();
		LoginPacketHandler::Init();
		WorldPacketHandler::Init();

		sPacketServiceTypeMap[Protocol::eServiceType::SERVICE_TYPE_HEARTBEAT] = [](const uint16 size, const uint16 packetId, const byte* pBuffer, const PacketSessionRef& pSession) -> bool
		{
			return HeartbeatPacketHandler::HandlePacket(size, packetId, pBuffer, pSession);
		};

		sPacketServiceTypeMap[Protocol::eServiceType::SERVICE_TYPE_LOGIN] = [](const uint16 size, const uint16 packetId, const byte* pBuffer, const PacketSessionRef& pSession) -> bool
		{
			return LoginPacketHandler::HandlePacket(size, packetId, pBuffer, pSession);
		};

		sPacketServiceTypeMap[Protocol::eServiceType::SERVICE_TYPE_WORLD] = [](const uint16 size, const uint16 packetId, const byte* pBuffer, const PacketSessionRef& pSession) -> bool
		{
			return WorldPacketHandler::HandlePacket(size, packetId, pBuffer, pSession);
		};


	}

	static bool HandlePacketServiceType(const uint16 len, const byte* pBuffer, const PacketSessionRef& pSession)
	{
		const auto [packetSize, headerId] = *(reinterpret_cast<const PacketHeader*>(pBuffer));

		const uint16 serviceType = GET_SERVICE_TYPE(headerId);
		const uint16 packetId = GET_PACKET_ID(headerId);

		const auto iter = sPacketServiceTypeMap.find(serviceType);
		if (iter != sPacketServiceTypeMap.end())
		{
			if (!SessionValidator::Validate(pSession))
			{
				return false;
			}

			return iter->second(packetSize, packetId, pBuffer, pSession);
		}

		return HANDLE_SERVICE_TYPE_INVALID(packetSize, packetId, pBuffer, pSession);
	}

	static bool HANDLE_SERVICE_TYPE_INVALID(const uint16 size, const uint16 packetId, const byte* pBuffer, const PacketSessionRef& pSession);

private:

	inline static HashMap<uint16, PacketServiceTypeHandle> sPacketServiceTypeMap;
};